// Fish Audio 4 — F4P02TwoProposals (1080x1920 @ 30fps, 160 frames)
// VO (assistant voice from the center node): "Two proposals are sitting
// unsent. One of them is your biggest deal this month."
//
// Cold-open demo. Continues the approved fish 3 system (FishBrainTalksBack):
// same amber speaking orb + constellation tree (shared SkillTreeWorld, Altari
// re-skin), hold -> move -> hold camera grammar.
//   f0-46   tight on the already-speaking center orb; the S2.1 Pro emotion-tag
//           input card slides in above it and typewrites the REAL product
//           input (VOICE_INPUTS.center — feature demo, not narration).
//   f46-64  18-frame travel to the Deals branch (focal from hubPos), two
//           routing pulses run ahead of the camera; branch highlights red.
//   f64-110 hold: "Harvey & Co" proposal card pops on the upper-chain node
//           ($48,000 value row, stronger glow), then "Meridian Group" on the
//           lower-chain node. Red unsent dots pulse.
//   f110-132 pull to z1.15 — both cards + speaking orb in frame.
//   f132-160 clean hold (identical keys).
// Compliance pill "Voice generated by Fish Audio" bottom-center from f10.
import React from "react";
import {
  AbsoluteFill,
  Audio,
  Easing,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { useAudioData, visualizeAudio } from "@remotion/media-utils";
import { loadFont as loadMono } from "@remotion/google-fonts/JetBrainsMono";
import { loadFont as loadInstrument } from "@remotion/google-fonts/InstrumentSerif";
import {
  ALTARI,
  API,
  AUDIO_LABEL,
  FISH,
  SPRINGS,
  TREE,
  VOICE_INPUTS,
} from "./theme";
import {
  AltariBackdrop,
  DEPT,
  HALF,
  SkillTreeWorld,
  hubPos,
  manropeFamily,
  proceduralBars,
} from "./tree";

// Real VO: Ahmed's clone speaking the line (drives the orb visualizer).
const AUDIO_SRC = "fish4/audio/center-two-proposals-ahmed-clone.mp3";
const AUDIO_FRAMES = 126; // 4.21s @ 30fps

const { fontFamily: monoFamily } = loadMono("normal", {
  weights: ["400", "500"],
});
const { fontFamily: instrumentFamily } = loadInstrument("italic", {
  weights: ["400"],
});

export const DURATION_IN_FRAMES = 160;

const VIEW_W = 1080;
const VIEW_H = 1920;

// Deterministic Deals-branch node coords (seed 99120711 in tree.tsx).
// Upper chain: (180.2,441.5)(130.5,408.6)(90.8,375.8)(70,350.7)(70,327.2)
// Lower chain: (160.6,515.3)(122.3,529.7)(70,531.2)
const HARVEY_NODE = { x: 90.8, y: 375.8 };
const MERIDIAN_NODE = { x: 122.3, y: 529.7 };

// World-space card boxes (kept inside 54px screen margins at every hold).
const HARVEY_CARD = { left: 84, top: 158, width: 312 };
const MERIDIAN_CARD = { left: 96, top: 584, width: 312 };

const INPUT_CARD = { left: 280, top: 170, width: 520, height: 176 };

const CENTER_INPUT = VOICE_INPUTS.center;
const TAG_END = CENTER_INPUT.lastIndexOf("]") + 1;

const ease = Easing.inOut(Easing.cubic);

// Timing
const TYPE_START = 12;
const TYPE_END = 40;
const INPUT_FADE = [46, 57] as const;
const HIGHLIGHT_AT = 60;
const HARVEY_AT = 78;
const HARVEY_VALUE_AT = 88;
const MERIDIAN_AT = 96;

const StatusDot: React.FC<{ frame: number; phase: number }> = ({
  frame,
  phase,
}) => {
  const pulse = 0.65 + 0.35 * Math.sin(frame * 0.28 + phase);
  return (
    <div
      style={{
        width: 11,
        height: 11,
        borderRadius: 999,
        backgroundColor: ALTARI.red,
        boxShadow: `0 0 ${8 + pulse * 8}px rgba(232,93,93,${0.4 + pulse * 0.35})`,
        opacity: 0.6 + pulse * 0.4,
        flexShrink: 0,
      }}
    />
  );
};

export const F4P02TwoProposals: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const dealsHub = hubPos(DEPT.Deals);

  // ---- Camera (one shared keyframe timeline) -----------------------------
  const KEY_T = [0, 26, 46, 64, 110, 132, DURATION_IN_FRAMES];
  const fx = interpolate(
    frame,
    KEY_T,
    [540, 540, 540, dealsHub.x + 20, dealsHub.x + 20, 370, 370],
    { easing: ease, extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const fy = interpolate(
    frame,
    KEY_T,
    [500, 415, 415, dealsHub.y - 55, dealsHub.y - 55, 470, 470],
    { easing: ease, extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const z = interpolate(
    frame,
    KEY_T,
    [1.74, 1.62, 1.62, 1.5, 1.5, 1.15, 1.15],
    { easing: ease, extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // ---- Tree state ---------------------------------------------------------
  const audioData = useAudioData(staticFile(AUDIO_SRC));
  let barValues = proceduralBars(frame, frame < AUDIO_FRAMES);
  if (audioData && frame < AUDIO_FRAMES) {
    barValues = visualizeAudio({
      fps,
      frame,
      audioData,
      numberOfSamples: HALF,
    }).map((v) => Math.min(1, Math.sqrt(v) * 2.4));
  } else if (audioData) {
    barValues = proceduralBars(frame, false);
  }
  const labelDim = interpolate(frame, [0, 100, 132], [0.35, 0.35, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // ---- Emotion-tag input card (typewriter, string slicing) ---------------
  const inputSlide = spring({
    frame: frame - 8,
    fps,
    config: SPRINGS.smooth,
  });
  const inputOpacity =
    interpolate(frame, [8, 22], [0, 1], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }) *
    interpolate(frame, [...INPUT_FADE], [1, 0], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    });
  const typedCount = Math.floor(
    interpolate(frame, [TYPE_START, TYPE_END], [0, CENTER_INPUT.length], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }),
  );
  const tagShown = CENTER_INPUT.slice(0, Math.min(typedCount, TAG_END));
  const restShown =
    typedCount > TAG_END ? CENTER_INPUT.slice(TAG_END, typedCount) : "";
  const cursorOn =
    typedCount < CENTER_INPUT.length ? true : frame % 16 < 8;

  // ---- Proposal cards -----------------------------------------------------
  const harveyIn = spring({
    frame: frame - HARVEY_AT,
    fps,
    config: { damping: 15, stiffness: 160 },
  });
  const harveyValueIn = spring({
    frame: frame - HARVEY_VALUE_AT,
    fps,
    config: SPRINGS.snappy,
  });
  const meridianIn = spring({
    frame: frame - MERIDIAN_AT,
    fps,
    config: { damping: 15, stiffness: 160 },
  });

  const cardTransform = (s: number) =>
    `translateY(${(1 - s) * 20}px) scale(${0.7 + 0.3 * s})`;

  // Leader-line draw progress
  const harveyLead = interpolate(frame, [HARVEY_AT - 2, HARVEY_AT + 8], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const meridianLead = interpolate(
    frame,
    [MERIDIAN_AT - 2, MERIDIAN_AT + 8],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  const harveyLeadFrom = { x: 140, y: 332 };
  const meridianLeadFrom = { x: 150, y: 582 };
  const leadLen = (a: { x: number; y: number }, b: { x: number; y: number }) =>
    Math.hypot(b.x - a.x, b.y - a.y);
  const hLen = leadLen(harveyLeadFrom, HARVEY_NODE);
  const mLen = leadLen(meridianLeadFrom, MERIDIAN_NODE);

  // One-shot ping rings on the anchor nodes as each card lands
  const ping = (start: number) => {
    const t = (frame - start) / 24;
    if (t < 0 || t > 1) return null;
    return { r: 12 + t * 24, opacity: 0.8 * (1 - t) };
  };
  const harveyPing = ping(HARVEY_AT - 2);
  const meridianPing = ping(MERIDIAN_AT - 2);

  // ---- Compliance pill (screen space) ------------------------------------
  const pillIn = interpolate(frame, [10, 20], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill style={{ backgroundColor: ALTARI.bg }}>
      {/* Static full-frame backdrop — does NOT move with the camera */}
      <AltariBackdrop width={VIEW_W} height={VIEW_H} />
      <Audio src={staticFile(AUDIO_SRC)} />

      {/* ---- Camera world ---- */}
      <div
        style={{
          position: "absolute",
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          transform: `translate(${VIEW_W / 2 - fx}px, ${VIEW_H / 2 - fy}px) scale(${z})`,
          transformOrigin: `${fx}px ${fy}px`,
        }}
      >
        <SkillTreeWorld
          frame={frame}
          revealAt={-120}
          labelDim={labelDim}
          highlightDept={frame >= HIGHLIGHT_AT ? DEPT.Deals : null}
          speaker="center"
          barValues={barValues}
          brainOpacity={0.5}
          orbIn={1}
          pulses={[
            { dept: DEPT.Deals, start: 46 },
            { dept: DEPT.Deals, start: 68 },
          ]}
        />

        {/* Leader lines + anchor rings (world space, above the tree) */}
        <svg
          viewBox="0 0 1080 1080"
          style={{
            position: "absolute",
            left: 0,
            top: 0,
            width: 1080,
            height: 1080,
            overflow: "visible",
          }}
        >
          <line
            x1={harveyLeadFrom.x}
            y1={harveyLeadFrom.y}
            x2={HARVEY_NODE.x}
            y2={HARVEY_NODE.y}
            stroke={ALTARI.red}
            strokeWidth={1.6}
            strokeDasharray={hLen}
            strokeDashoffset={hLen * (1 - harveyLead)}
            opacity={0.7 * Math.min(1, harveyIn * 1.4)}
          />
          <circle
            cx={HARVEY_NODE.x}
            cy={HARVEY_NODE.y}
            r={14}
            fill="none"
            stroke={ALTARI.red}
            strokeWidth={1.6}
            opacity={0.55 * Math.min(1, harveyIn * 1.4)}
          />
          {harveyPing && (
            <circle
              cx={HARVEY_NODE.x}
              cy={HARVEY_NODE.y}
              r={harveyPing.r}
              fill="none"
              stroke={ALTARI.red}
              strokeWidth={2}
              opacity={harveyPing.opacity}
            />
          )}
          <line
            x1={meridianLeadFrom.x}
            y1={meridianLeadFrom.y}
            x2={MERIDIAN_NODE.x}
            y2={MERIDIAN_NODE.y}
            stroke={ALTARI.red}
            strokeWidth={1.6}
            strokeDasharray={mLen}
            strokeDashoffset={mLen * (1 - meridianLead)}
            opacity={0.7 * Math.min(1, meridianIn * 1.4)}
          />
          <circle
            cx={MERIDIAN_NODE.x}
            cy={MERIDIAN_NODE.y}
            r={14}
            fill="none"
            stroke={ALTARI.red}
            strokeWidth={1.6}
            opacity={0.55 * Math.min(1, meridianIn * 1.4)}
          />
          {meridianPing && (
            <circle
              cx={MERIDIAN_NODE.x}
              cy={MERIDIAN_NODE.y}
              r={meridianPing.r}
              fill="none"
              stroke={ALTARI.red}
              strokeWidth={2}
              opacity={meridianPing.opacity}
            />
          )}
        </svg>

        {/* ---- Emotion-tag input card (S2.1 Pro product input) ---- */}
        {inputOpacity > 0.001 && (
          <div
            style={{
              position: "absolute",
              left: INPUT_CARD.left,
              top: INPUT_CARD.top,
              width: INPUT_CARD.width,
              height: INPUT_CARD.height,
              backgroundColor: ALTARI.card2,
              border: `1px solid ${ALTARI.border}`,
              borderRadius: 18,
              padding: "18px 24px",
              boxSizing: "border-box",
              boxShadow: "0 18px 48px rgba(10,10,24,0.45)",
              opacity: inputOpacity,
              transform: `translateY(${(1 - inputSlide) * -40}px)`,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 9,
                marginBottom: 12,
              }}
            >
              <div
                style={{
                  width: 7,
                  height: 7,
                  borderRadius: 999,
                  backgroundColor: ALTARI.primaryLight,
                }}
              />
              <span
                style={{
                  fontFamily: monoFamily,
                  fontWeight: 400,
                  fontSize: 15,
                  letterSpacing: 1,
                  color: ALTARI.faint,
                }}
              >
                {API.model}
              </span>
            </div>
            <div
              style={{
                fontFamily: monoFamily,
                fontWeight: 400,
                fontSize: 20,
                lineHeight: "31px",
                wordBreak: "break-word",
              }}
            >
              <span style={{ color: TREE.orb }}>{tagShown}</span>
              <span style={{ color: ALTARI.body }}>{restShown}</span>
              {cursorOn && (
                <span
                  style={{
                    display: "inline-block",
                    width: 10,
                    height: 20,
                    marginLeft: 2,
                    verticalAlign: "-3px",
                    backgroundColor: TREE.cream,
                  }}
                />
              )}
            </div>
          </div>
        )}

        {/* ---- Harvey & Co proposal card (the biggest deal) ---- */}
        {harveyIn > 0.01 && (
          <div
            style={{
              position: "absolute",
              left: HARVEY_CARD.left,
              top: HARVEY_CARD.top,
              width: HARVEY_CARD.width,
              backgroundColor: ALTARI.card,
              border: "1px solid #4A4A78",
              borderRadius: 16,
              padding: "20px 22px",
              boxSizing: "border-box",
              boxShadow:
                "0 0 54px rgba(232,162,91,0.22), 0 16px 40px rgba(10,10,24,0.5)",
              opacity: Math.min(1, harveyIn * 1.6),
              transform: cardTransform(harveyIn),
              transformOrigin: "50% 100%",
            }}
          >
            <div
              style={{
                fontFamily: manropeFamily,
                fontWeight: 700,
                fontSize: 30,
                lineHeight: "36px",
                color: ALTARI.heading,
              }}
            >
              Harvey &amp; Co
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                marginTop: 9,
              }}
            >
              <StatusDot frame={frame} phase={0} />
              <span
                style={{
                  fontFamily: manropeFamily,
                  fontWeight: 500,
                  fontSize: 20,
                  color: ALTARI.body,
                }}
              >
                Proposal · unsent
              </span>
            </div>
            <div
              style={{
                marginTop: 10,
                fontFamily: instrumentFamily,
                fontStyle: "italic",
                fontWeight: 400,
                fontSize: 46,
                lineHeight: "52px",
                color: TREE.cream,
                opacity: harveyValueIn,
                transform: `translateY(${(1 - harveyValueIn) * 10}px)`,
              }}
            >
              $48,000
            </div>
          </div>
        )}

        {/* ---- Meridian Group proposal card ---- */}
        {meridianIn > 0.01 && (
          <div
            style={{
              position: "absolute",
              left: MERIDIAN_CARD.left,
              top: MERIDIAN_CARD.top,
              width: MERIDIAN_CARD.width,
              backgroundColor: ALTARI.card,
              border: `1px solid ${ALTARI.border}`,
              borderRadius: 16,
              padding: "20px 22px",
              boxSizing: "border-box",
              boxShadow: "0 16px 40px rgba(10,10,24,0.5)",
              opacity: Math.min(1, meridianIn * 1.6),
              transform: cardTransform(meridianIn),
              transformOrigin: "50% 0%",
            }}
          >
            <div
              style={{
                fontFamily: manropeFamily,
                fontWeight: 700,
                fontSize: 30,
                lineHeight: "36px",
                color: ALTARI.heading,
              }}
            >
              Meridian Group
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                marginTop: 9,
              }}
            >
              <StatusDot frame={frame} phase={2.1} />
              <span
                style={{
                  fontFamily: manropeFamily,
                  fontWeight: 500,
                  fontSize: 20,
                  color: ALTARI.body,
                }}
              >
                Proposal · unsent
              </span>
            </div>
          </div>
        )}
      </div>

      {/* Vignette (screen space, Altari-tinted — matches the fish 3 grade) */}
      <AbsoluteFill
        style={{
          background:
            "radial-gradient(140% 130% at 50% 48%, rgba(0,0,0,0) 55%, rgba(10,10,24,0.5) 100%)",
          pointerEvents: "none",
        }}
      />

      {/* Compliance pill — required brand label, inside safe zones */}
      <div
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          top: 1608,
          display: "flex",
          justifyContent: "center",
          opacity: pillIn,
          transform: `translateY(${(1 - pillIn) * 14}px)`,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            padding: "12px 24px",
            borderRadius: 999,
            backgroundColor: "rgba(37,37,66,0.9)",
            border: `1px solid ${ALTARI.border}`,
          }}
        >
          <div
            style={{
              width: 9,
              height: 9,
              borderRadius: 999,
              backgroundColor: FISH.orange,
            }}
          />
          <span
            style={{
              fontFamily: manropeFamily,
              fontWeight: 600,
              fontSize: 25,
              letterSpacing: 0.4,
              color: ALTARI.body,
            }}
          >
            {AUDIO_LABEL}
          </span>
        </div>
      </div>
    </AbsoluteFill>
  );
};
