// Fish Audio 4 — F4P07HarveyOpenSince (1080x1920 @ 30fps)
// VO (Deals dept voice): "Harvey. It's been open since Tuesday and pricing is
// the only thing left on it."
// The DEPARTMENT answers: bars radiate from the Deals hub (not the center).
// The proposal's actual state is shown as UI — never as narration text.
//
// Beat map (continues F4P01 + fish3 approved camera language):
//   f0–48    open tight on the Deals hub ALREADY speaking (red ring, red bars),
//            slow push-in z 2.50 → 2.68. Emotion-tag input card slides in from
//            the top at f10; S2.1 Pro input types via string slicing f14–50.
//   f10      compliance chip "Voice generated by Fish Audio" fades in bottom.
//   f48–68   ONE 20-frame pull-back (z → 1.58, focal drifts toward the Deals
//            branch constellation; the distant particle brain enters lower-right
//            — the hub belongs to a larger system).
//   f75–130  proposal card springs in as a floating UI fragment: title, meta
//            "Opened · Tuesday", checklist Scope/Timeline/Team ✓ green, Pricing
//            with a pulsing amber dot. Rows stagger in 4-frame steps.
//   f130–170 settle: input card + proposal card + speaking hub composed in the
//            vertical frame; final 25+ frames clean hold (bars micro-motion,
//            pricing dot pulsing, cursor blinking).
import React from "react";
import {
  AbsoluteFill,
  Audio,
  Easing,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { loadFont as loadMono } from "@remotion/google-fonts/JetBrainsMono";
import { useAudioData, visualizeAudio } from "@remotion/media-utils";
import { ALTARI, API, AUDIO_LABEL, VOICE_INPUTS } from "./theme";

// Real VO: the Deals-branch voice (Fish Audio library "Adrian") — drives the hub bars.
const AUDIO_SRC = "fish4/audio/deals-harvey-adrian.mp3";
const AUDIO_FRAMES = 169; // 5.64s @ 30fps
import {
  AltariBackdrop,
  DEPARTMENTS,
  DEPT,
  HALF,
  SkillTreeWorld,
  manropeFamily,
  proceduralBars,
} from "./tree";

export const DURATION_IN_FRAMES = 200; // audio runs to f176 + settle hold

const W = 1080;
const H = 1920;

const { fontFamily: monoFamily } = loadMono("normal", {
  weights: ["400", "500"],
});

const DEALS_RED = DEPARTMENTS[DEPT.Deals].color; // #E85D5D
const ease = Easing.inOut(Easing.cubic);

// Proposal checklist — UI state data (allowed), not narration.
const CHECK_ROWS = [
  { label: "Scope", done: true },
  { label: "Timeline", done: true },
  { label: "Team", done: true },
  { label: "Pricing", done: false },
] as const;

const CheckIcon: React.FC = () => (
  <svg width={30} height={30} viewBox="0 0 30 30">
    <circle
      cx={15}
      cy={15}
      r={13}
      fill="rgba(78,205,155,0.12)"
      stroke={ALTARI.green}
      strokeWidth={1.8}
    />
    <path
      d="M9.5 15.5 L13.4 19.4 L20.8 11.4"
      fill="none"
      stroke={ALTARI.green}
      strokeWidth={2.6}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

const PendingDot: React.FC<{ frame: number }> = ({ frame }) => {
  const p = (frame % 34) / 34;
  return (
    <svg width={30} height={30} viewBox="0 0 30 30">
      <circle
        cx={15}
        cy={15}
        r={6 + p * 8.5}
        fill="none"
        stroke={ALTARI.amber}
        strokeWidth={1.6}
        opacity={(1 - p) * 0.55}
      />
      <circle
        cx={15}
        cy={15}
        r={5.5}
        fill={ALTARI.amber}
        opacity={0.72 + 0.28 * Math.sin(frame * 0.3)}
      />
      <circle cx={15} cy={15} r={2.4} fill={DEALS_RED} opacity={0.9} />
    </svg>
  );
};

export const F4P07HarveyOpenSince: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // ---- Camera: one world, one shared keyframe timeline --------------------
  // Deals hub sits at world (≈258, ≈500). Open tight on it, pull back once.
  const KEY_T = [0, 48, 68, 130, 150, DURATION_IN_FRAMES];
  const clamp = {
    easing: ease,
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  } as const;
  const z = interpolate(frame, KEY_T, [2.5, 2.68, 1.58, 1.52, 1.52, 1.52], clamp);
  const fx = interpolate(frame, KEY_T, [265, 265, 360, 360, 360, 360], clamp);
  const fy = interpolate(frame, KEY_T, [470, 470, 330, 330, 330, 330], clamp);
  const worldTransform = `translate(${W / 2 - fx * z}px, ${
    H / 2 - fy * z
  }px) scale(${z})`;

  // ---- The Deals hub is already speaking from frame 0 ---------------------
  const audioData = useAudioData(staticFile(AUDIO_SRC));
  let barValues = proceduralBars(frame, frame < AUDIO_FRAMES, 3);
  if (audioData && frame < AUDIO_FRAMES) {
    barValues = visualizeAudio({
      fps,
      frame,
      audioData,
      numberOfSamples: HALF,
    }).map((v) => Math.min(1, Math.sqrt(v) * 2.4));
  } else if (audioData) {
    barValues = proceduralBars(frame, false, 3);
  }

  // Map labels recede a touch once the proposal card lands
  const labelDim = interpolate(frame, [70, 92], [0, 0.35], clamp);

  // ---- Emotion-tag input card (real S2.1 Pro input — feature demo) --------
  const inputIn = spring({
    frame: frame - 10,
    fps,
    config: { damping: 18, stiffness: 140 },
  });
  // Panel goes opaque fast so the map labels never bleed through mid-entrance
  const inputFade = interpolate(frame, [10, 17], [0, 1], {
    easing: Easing.out(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const fullInput = VOICE_INPUTS.deals;
  const tagEnd = fullInput.lastIndexOf("]") + 1;
  const typedChars = Math.floor(
    interpolate(frame, [14, 50], [0, fullInput.length], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }),
  );
  const typedTag = fullInput.slice(0, Math.min(typedChars, tagEnd));
  const typedRest = typedChars > tagEnd ? fullInput.slice(tagEnd, typedChars) : "";
  const cursorOn = Math.floor(frame / 8) % 2 === 0;

  // ---- Proposal card (floating UI fragment) -------------------------------
  const cardIn = spring({
    frame: frame - 75,
    fps,
    config: { damping: 17, stiffness: 130 },
  });
  const rowIn = (i: number) =>
    spring({
      frame: frame - (80 + i * 4),
      fps,
      config: { damping: 16, stiffness: 170 },
    });

  // ---- Compliance chip (required on audio demos) --------------------------
  const chipIn = interpolate(frame, [10, 24], [0, 1], {
    easing: Easing.out(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill style={{ backgroundColor: ALTARI.bg }}>
      {/* Opaque Altari base — full frame, frame 0 → last, never moves */}
      <AltariBackdrop width={W} height={H} />
      <Audio src={staticFile(AUDIO_SRC)} />

      {/* One world, one camera */}
      <div
        style={{
          position: "absolute",
          left: 0,
          top: 0,
          width: W,
          height: H,
          transform: worldTransform,
          transformOrigin: "0 0",
        }}
      >
        <SkillTreeWorld
          frame={frame}
          revealAt={-120}
          labelDim={labelDim}
          highlightDept={DEPT.Deals}
          speaker={DEPT.Deals}
          barValues={barValues}
          orbIn={1}
        />
      </div>

      {/* Emotion-tag input card — screen space, slides in from above */}
      <div
        style={{
          position: "absolute",
          left: (W - 900) / 2,
          top: 220,
          width: 900,
          backgroundColor: ALTARI.card2,
          border: `1px solid ${ALTARI.border}`,
          borderRadius: 18,
          padding: "26px 30px 24px",
          boxShadow: "0 24px 60px rgba(10, 10, 26, 0.5)",
          opacity: inputFade,
          transform: `translateY(${(1 - inputIn) * -56}px)`,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            marginBottom: 14,
          }}
        >
          <div
            style={{
              width: 9,
              height: 9,
              borderRadius: "50%",
              backgroundColor: DEALS_RED,
              opacity: 0.7 + 0.3 * Math.sin(frame * 0.26),
            }}
          />
          <div
            style={{
              fontFamily: monoFamily,
              fontWeight: 400,
              fontSize: 20,
              letterSpacing: 0.6,
              color: ALTARI.faint,
            }}
          >
            model: {API.model}
          </div>
        </div>
        <div
          style={{
            fontFamily: monoFamily,
            fontWeight: 400,
            fontSize: 31,
            lineHeight: 1.5,
            wordBreak: "break-word",
          }}
        >
          <span style={{ color: DEALS_RED }}>{typedTag}</span>
          <span style={{ color: ALTARI.heading }}>{typedRest}</span>
          <span
            style={{
              display: "inline-block",
              width: 15,
              height: 32,
              marginLeft: 3,
              verticalAlign: "text-bottom",
              backgroundColor: ALTARI.primaryLight,
              opacity: cursorOn ? 0.9 : 0,
            }}
          />
        </div>
      </div>

      {/* Proposal card — the actual state the department is reporting */}
      <div
        style={{
          position: "absolute",
          left: (W - 820) / 2,
          top: 540,
          width: 820,
          backgroundColor: ALTARI.card,
          border: `1px solid ${ALTARI.border}`,
          borderRadius: 20,
          padding: "34px 38px 26px",
          boxShadow: "0 28px 70px rgba(10, 10, 26, 0.55)",
          opacity: Math.min(1, cardIn * 1.5),
          transform: `translateY(${(1 - cardIn) * 36}px) scale(${
            0.94 + 0.06 * cardIn
          })`,
          transformOrigin: "50% 20%",
        }}
      >
        <div
          style={{
            fontFamily: manropeFamily,
            fontWeight: 700,
            fontSize: 40,
            color: ALTARI.heading,
            letterSpacing: 0.2,
          }}
        >
          Harvey &amp; Co — Proposal
        </div>
        <div
          style={{
            fontFamily: manropeFamily,
            fontWeight: 500,
            fontSize: 28,
            color: ALTARI.body,
            marginTop: 8,
          }}
        >
          Opened · Tuesday
        </div>
        <div
          style={{
            height: 1,
            backgroundColor: ALTARI.border,
            margin: "22px 0 8px",
          }}
        />
        {CHECK_ROWS.map((row, i) => {
          const rin = rowIn(i);
          return (
            <div
              key={row.label}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "14px 2px",
                borderBottom:
                  i < CHECK_ROWS.length - 1
                    ? `1px solid rgba(61, 61, 96, 0.5)`
                    : "none",
                opacity: Math.min(1, rin * 1.4),
                transform: `translateY(${(1 - rin) * 14}px)`,
              }}
            >
              <div
                style={{
                  fontFamily: manropeFamily,
                  fontWeight: 600,
                  fontSize: 32,
                  color: row.done ? ALTARI.heading : ALTARI.amber,
                }}
              >
                {row.label}
              </div>
              {row.done ? <CheckIcon /> : <PendingDot frame={frame} />}
            </div>
          );
        })}
      </div>

      {/* Brand compliance chip — bottom-center, above the Reels UI zone */}
      <div
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          bottom: 250,
          display: "flex",
          justifyContent: "center",
          opacity: chipIn,
          transform: `translateY(${(1 - chipIn) * 10}px)`,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 9,
            backgroundColor: ALTARI.card,
            border: `1px solid ${ALTARI.border}`,
            borderRadius: 999,
            padding: "9px 18px",
            fontFamily: manropeFamily,
            fontWeight: 500,
            fontSize: 17,
            letterSpacing: 0.4,
            color: ALTARI.body,
          }}
        >
          <div
            style={{
              width: 7,
              height: 7,
              borderRadius: "50%",
              backgroundColor: ALTARI.amber,
              opacity: 0.72 + 0.28 * Math.sin(frame * 0.28),
            }}
          />
          {AUDIO_LABEL}
        </div>
      </div>
    </AbsoluteFill>
  );
};
