// Fish Audio 4 — F4P01EveryonesBuilding (1080x1080 @ 30fps)
// VO: "Everyone's building these flashy agent dashboards. This one actually talks back."
// The HOOK: open on the full established Skilltree map alive and glittering,
// slow push-in, then the amber center orb ignites — it literally talks back.
// Beat map:
//   f0–30   full tree established, slow push-in (zoom 1.00 → 1.08)
//   f30–56  hold → move (18f) → hold, push continues to 1.16
//   f58–90  the turn: center orb ignites at f60 during the hold, bars burst,
//           brain particles condense (brainOpacity 0.95 → 0.45)
//   f70     compliance chip "Voice generated by Fish Audio" fades in bottom-center
//   f80–95  final move to zoom 1.30 on the speaking orb
//   f95–120 clean hold (bars keep micro-motion)
import React from "react";
import {
  AbsoluteFill,
  Easing,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { ALTARI, AUDIO_LABEL } from "./theme";
import {
  AltariBackdrop,
  CX,
  CY,
  SkillTreeWorld,
  manropeFamily,
  proceduralBars,
} from "./tree";

export const DURATION_IN_FRAMES = 120;

const W = 1080;
const H = 1080;

export const F4P01EveryonesBuilding: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // ---- Camera: one shared keyframe timeline, hold → move → hold -----------
  // Focal point is the world center (the orb); only zoom travels.
  // Orb ignition (f60) lands inside the f56–80 hold — action during a hold.
  const KEY_T = [0, 30, 38, 56, 80, 95, 118, DURATION_IN_FRAMES];
  const KEY_Z = [1.0, 1.08, 1.08, 1.16, 1.16, 1.3, 1.3, 1.3];
  const zoom = interpolate(frame, KEY_T, KEY_Z, {
    easing: Easing.inOut(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const worldTransform = `translate(${W / 2 - CX * zoom}px, ${
    H / 2 - CY * zoom
  }px) scale(${zoom})`;

  // ---- The turn: orb ignites at f60, brain condenses under it -------------
  const orbIn = spring({
    frame: frame - 60,
    fps,
    config: { damping: 16, stiffness: 120 },
  });
  const brainOpacity = interpolate(frame, [58, 92], [0.95, 0.45], {
    easing: Easing.inOut(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const barValues = proceduralBars(frame, frame > 62);

  // Labels recede slightly as the camera settles close on the orb
  const labelDim = interpolate(frame, [78, 100], [0, 0.45], {
    easing: Easing.inOut(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // ---- Compliance chip (required on audio demos) --------------------------
  const chipIn = interpolate(frame, [70, 84], [0, 1], {
    easing: Easing.out(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill style={{ backgroundColor: ALTARI.bg }}>
      {/* Opaque Altari base — full frame, frame 0 → last, never moves */}
      <AltariBackdrop width={W} height={H} />

      {/* One world, one camera */}
      <div
        style={{
          position: "absolute",
          left: 0,
          top: 0,
          width: W,
          height: H,
          transform: worldTransform,
          transformOrigin: "0 0",
        }}
      >
        <SkillTreeWorld
          frame={frame}
          revealAt={-120}
          labelDim={labelDim}
          speaker="center"
          barValues={barValues}
          brainOpacity={brainOpacity}
          orbIn={orbIn > 0.01 ? orbIn : 0}
        />
      </div>

      {/* Brand compliance chip — screen space, bottom-center, inside safe margins */}
      <div
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          bottom: 100,
          display: "flex",
          justifyContent: "center",
          opacity: chipIn,
          transform: `translateY(${(1 - chipIn) * 10}px)`,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 9,
            backgroundColor: ALTARI.card,
            border: `1px solid ${ALTARI.border}`,
            borderRadius: 999,
            padding: "9px 18px",
            fontFamily: manropeFamily,
            fontWeight: 500,
            fontSize: 17,
            letterSpacing: 0.4,
            color: ALTARI.body,
          }}
        >
          <div
            style={{
              width: 7,
              height: 7,
              borderRadius: "50%",
              backgroundColor: ALTARI.amber,
              opacity: 0.72 + 0.28 * Math.sin(frame * 0.28),
            }}
          />
          {AUDIO_LABEL}
        </div>
      </div>
    </AbsoluteFill>
  );
};
