// Fish Audio 4 — F4P11OnboardingFine (1080x1080 @ 30fps)
// VO (Operations dept Voice Design voice, dry): two-beat status report.
// Beat 1 reports OK on Ops turf; beat 2 throws the warning across the map to
// Back Office, where the trouble lives. The map's real sub-labels carry the
// meaning — no narration text on screen.
//
// Beat map:
//   f0–30   close on the Operations hub SPEAKING (radial bars, teal highlight);
//           3 Ops branch nodes pulse GREEN ("all fine" status ticks)
//   f30–62  the turn: an amber warning dot arcs from the Ops hub across the map
//           to the Back Office hub ($, bottom) while the camera whips with it
//           (hold → 18f move w/ zoom dip → hold)
//   f62–105 3 Back Office branch nodes blink amber→red (repeating soft blink),
//           the $ hub ring glows warm-red; Ops bars fade out by f75;
//           final ~40 frames are a clean hold on the breathing warning
//   f8      compliance chip "Voice generated by Fish Audio" in (screen space)
import React from "react";
import {
  AbsoluteFill,
  Audio,
  Easing,
  interpolate,
  interpolateColors,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { useAudioData, visualizeAudio } from "@remotion/media-utils";
import { ALTARI, AUDIO_LABEL } from "./theme";
import {
  AltariBackdrop,
  DEPT,
  HALF,
  SkillTreeWorld,
  buildBranches,
  hubPos,
  manropeFamily,
  proceduralBars,
} from "./tree";

// Real VO: the Ops-branch voice (Fish Audio library "Ethan") — drives the hub bars.
const AUDIO_SRC = "fish4/audio/ops-onboarding-ethan.mp3";
const AUDIO_FRAMES = 74; // 2.48s @ 30fps

export const DURATION_IN_FRAMES = 105;

const W = 1080;
const H = 1080;

// Ops branch nodes that pulse green (indices into branches[DEPT.Operations].nodes,
// chosen to sit clear of the "OPERATIONS / onboarding · builds · client ops" label)
const GREEN_IDX = [1, 2, 4];
// Back Office branch nodes that blink amber→red (triangle spread around the $ hub)
const WARN_IDX = [7, 0, 2];

const ease = Easing.inOut(Easing.cubic);
const clamp = {
  easing: ease,
  extrapolateLeft: "clamp",
  extrapolateRight: "clamp",
} as const;

export const F4P11OnboardingFine: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const branches = React.useMemo(buildBranches, []);
  const opsNodes = branches[DEPT.Operations].nodes;
  const boNodes = branches[DEPT.BackOffice].nodes;
  const opsHub = hubPos(DEPT.Operations); // (691.0, 298.3)
  const boHub = hubPos(DEPT.BackOffice); // (540.0, 825.0)

  // ---- Camera: hold on Ops → 18f whip (zoom dips to reveal the map) → hold --
  const KEY_T = [0, 36, 54, 62, 103, 105];
  const fx = interpolate(frame, KEY_T, [700, 700, 540, 540, 540, 540], clamp);
  const fy = interpolate(frame, KEY_T, [270, 270, 850, 855, 855, 855], clamp);
  const zoom = interpolate(
    frame,
    [0, 36, 45, 54, 62, 103, 105],
    [1.9, 1.9, 1.3, 1.5, 1.55, 1.55, 1.55],
    clamp,
  );
  const worldTransform = `translate(${W / 2 - fx * zoom}px, ${
    H / 2 - fy * zoom
  }px) scale(${zoom})`;

  // ---- Ops speaking: bars live from f0, speech ends ~f68, gone by f75 -------
  const orbIn = interpolate(frame, [AUDIO_FRAMES, AUDIO_FRAMES + 12], [1, 0.02], clamp);
  const audioData = useAudioData(staticFile(AUDIO_SRC));
  let barValues = proceduralBars(frame, frame < AUDIO_FRAMES, 5);
  if (audioData && frame < AUDIO_FRAMES) {
    barValues = visualizeAudio({
      fps,
      frame,
      audioData,
      numberOfSamples: HALF,
    }).map((v) => Math.min(1, Math.sqrt(v) * 2.4));
  } else if (audioData) {
    barValues = proceduralBars(frame, false, 5);
  }

  // Highlight follows the story: Ops turf first, Back Office once the warning lands
  const highlightDept = frame < 54 ? DEPT.Operations : DEPT.BackOffice;

  // ---- Beat 1: green "all fine" pulses on Ops nodes -------------------------
  const greenOut = interpolate(frame, [28, 38], [1, 0], clamp);

  // ---- Beat 2: warning dot arcs Ops hub → Back Office hub -------------------
  // Quadratic bezier, bowed gently right of the straight line across the map.
  const ARC_C = { x: 770, y: 575 };
  const dotT = interpolate(frame, [35, 53], [0, 1], clamp);
  const arcAt = (t: number) => {
    const u = 1 - t;
    return {
      x: u * u * opsHub.x + 2 * u * t * ARC_C.x + t * t * boHub.x,
      y: u * u * opsHub.y + 2 * u * t * ARC_C.y + t * t * boHub.y,
    };
  };
  const dotFade = interpolate(frame, [53, 57], [1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // ---- Beat 3: Back Office warning state ------------------------------------
  const warnIn = spring({
    frame: frame - 53,
    fps,
    config: { damping: 14, stiffness: 110 },
  });

  // ---- Compliance chip (required on audio demos) ----------------------------
  const chipIn = interpolate(frame, [8, 20], [0, 1], {
    easing: Easing.out(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const hubPulse = 0.5 + 0.5 * Math.sin((frame - 53) * 0.19);
  const hubWarnColor = interpolateColors(
    hubPulse,
    [0, 1],
    [ALTARI.amber, ALTARI.red],
  );

  return (
    <AbsoluteFill style={{ backgroundColor: ALTARI.bg }}>
      {/* Opaque Altari base — full frame, frame 0 → last, never moves */}
      <AltariBackdrop width={W} height={H} />
      <Audio src={staticFile(AUDIO_SRC)} />

      {/* One world, one camera */}
      <div
        style={{
          position: "absolute",
          left: 0,
          top: 0,
          width: W,
          height: H,
          transform: worldTransform,
          transformOrigin: "0 0",
        }}
      >
        <SkillTreeWorld
          frame={frame}
          revealAt={-120}
          labelDim={0}
          highlightDept={highlightDept}
          speaker={DEPT.Operations}
          barValues={barValues}
          orbIn={orbIn}
        />

        {/* Status overlays — same world coordinates, drawn over the tree */}
        <svg
          viewBox={`0 0 ${W} ${H}`}
          style={{
            position: "absolute",
            left: 0,
            top: 0,
            width: W,
            height: H,
            overflow: "visible",
          }}
        >
          <defs>
            <filter id="f4p11soft" x="-120%" y="-120%" width="340%" height="340%">
              <feGaussianBlur stdDeviation="14" />
            </filter>
          </defs>

          {/* Beat 1 — green status ticks on the Ops branch */}
          {greenOut > 0.01 &&
            GREEN_IDX.map((idx, k) => {
              const n = opsNodes[idx];
              const start = 4 + k * 7;
              if (frame < start) return null;
              const local = frame - start;
              const popIn = Math.min(1, local / 6);
              const wave = (local % 16) / 16;
              const s01 = 0.5 + 0.5 * Math.sin(local * 0.32);
              return (
                <g key={`g${idx}`} opacity={greenOut}>
                  <circle
                    cx={n.x}
                    cy={n.y}
                    r={n.r + 3 + wave * 12}
                    fill="none"
                    stroke={ALTARI.green}
                    strokeWidth={1.8}
                    opacity={(1 - wave) * 0.8 * popIn}
                  />
                  <circle
                    cx={n.x}
                    cy={n.y}
                    r={n.r + 1.5}
                    fill="none"
                    stroke={ALTARI.green}
                    strokeWidth={2.2}
                    opacity={(0.55 + 0.35 * s01) * popIn}
                  />
                  <circle
                    cx={n.x}
                    cy={n.y}
                    r={Math.max(1.5, n.r - 1.5)}
                    fill={ALTARI.green}
                    opacity={(0.5 + 0.3 * s01) * popIn}
                  />
                </g>
              );
            })}

          {/* Beat 2 — launch flash at the Ops hub */}
          {frame >= 33 && frame <= 43 && (
            <circle
              cx={opsHub.x}
              cy={opsHub.y}
              r={38 + ((frame - 33) / 10) * 34}
              fill="none"
              stroke={ALTARI.amber}
              strokeWidth={2.4 - ((frame - 33) / 10) * 1.8}
              opacity={(1 - (frame - 33) / 10) * 0.7}
            />
          )}

          {/* Beat 2 — the traveling warning dot + trail */}
          {frame >= 35 &&
            frame <= 57 &&
            (() => {
              const p = arcAt(dotT);
              const trail = [0.055, 0.11, 0.17].map((off, i) => {
                const tp = arcAt(Math.max(0, dotT - off));
                return (
                  <circle
                    key={`t${i}`}
                    cx={tp.x}
                    cy={tp.y}
                    r={4.6 - i * 1.2}
                    fill={ALTARI.amber}
                    opacity={(0.42 - i * 0.13) * dotFade}
                  />
                );
              });
              return (
                <g>
                  {trail}
                  <circle
                    cx={p.x}
                    cy={p.y}
                    r={15}
                    fill={ALTARI.amber}
                    opacity={0.32 * dotFade}
                    filter="url(#f4p11soft)"
                  />
                  <circle
                    cx={p.x}
                    cy={p.y}
                    r={6.5}
                    fill={ALTARI.amber}
                    opacity={dotFade}
                  />
                  <circle
                    cx={p.x}
                    cy={p.y}
                    r={3}
                    fill="#FFE9CC"
                    opacity={dotFade}
                  />
                </g>
              );
            })()}

          {/* Beat 3 — impact ring where the warning lands */}
          {frame >= 52 && frame <= 66 && (
            <circle
              cx={boHub.x}
              cy={boHub.y}
              r={36 + ((frame - 52) / 14) * 52}
              fill="none"
              stroke={interpolateColors(
                (frame - 52) / 14,
                [0, 1],
                [ALTARI.amber, ALTARI.red],
              )}
              strokeWidth={2.6 - ((frame - 52) / 14) * 1.8}
              opacity={(1 - (frame - 52) / 14) * 0.85}
            />
          )}

          {/* Beat 3 — $ hub ring breathes warm-red */}
          {warnIn > 0.01 && (
            <g>
              <circle
                cx={boHub.x}
                cy={boHub.y}
                r={62 + hubPulse * 8}
                fill={ALTARI.red}
                opacity={warnIn * (0.1 + 0.08 * hubPulse)}
                filter="url(#f4p11soft)"
              />
              <circle
                cx={boHub.x}
                cy={boHub.y}
                r={44}
                fill="none"
                stroke={hubWarnColor}
                strokeWidth={2.4}
                opacity={warnIn * (0.5 + 0.35 * hubPulse)}
              />
              <circle
                cx={boHub.x}
                cy={boHub.y}
                r={54 + hubPulse * 4}
                fill="none"
                stroke={ALTARI.red}
                strokeWidth={1.2}
                opacity={warnIn * 0.3}
              />
            </g>
          )}

          {/* Beat 3 — amber→red blinking warnings on Back Office nodes */}
          {WARN_IDX.map((idx, k) => {
            const n = boNodes[idx];
            const start = 58 + k * 6;
            if (frame < start) return null;
            const pop = spring({
              frame: frame - start,
              fps,
              config: { damping: 12, stiffness: 150 },
            });
            const s01 = 0.5 + 0.5 * Math.sin((frame - start) * 0.24 + k * 1.4);
            const warnColor = interpolateColors(
              s01,
              [0, 1],
              [ALTARI.amber, ALTARI.red],
            );
            return (
              <g key={`w${idx}`}>
                <circle
                  cx={n.x}
                  cy={n.y}
                  r={n.r + 13 + s01 * 4}
                  fill={warnColor}
                  opacity={pop * (0.09 + 0.09 * s01)}
                />
                <circle
                  cx={n.x}
                  cy={n.y}
                  r={n.r + 4.5 + s01 * 2.5}
                  fill="none"
                  stroke={warnColor}
                  strokeWidth={2.2}
                  opacity={pop * (0.45 + 0.4 * s01)}
                />
                <circle
                  cx={n.x}
                  cy={n.y}
                  r={Math.max(2, n.r - 1)}
                  fill={warnColor}
                  opacity={pop * (0.55 + 0.35 * s01)}
                />
              </g>
            );
          })}
        </svg>
      </div>

      {/* Brand compliance chip — screen space, bottom-center, inside safe margins */}
      <div
        style={{
          position: "absolute",
          left: 0,
          right: 0,
          bottom: 100,
          display: "flex",
          justifyContent: "center",
          opacity: chipIn,
          transform: `translateY(${(1 - chipIn) * 10}px)`,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 9,
            backgroundColor: ALTARI.card,
            border: `1px solid ${ALTARI.border}`,
            borderRadius: 999,
            padding: "9px 18px",
            fontFamily: manropeFamily,
            fontWeight: 500,
            fontSize: 17,
            letterSpacing: 0.4,
            color: ALTARI.body,
          }}
        >
          <div
            style={{
              width: 7,
              height: 7,
              borderRadius: "50%",
              backgroundColor: ALTARI.amber,
              opacity: 0.72 + 0.28 * Math.sin(frame * 0.28),
            }}
          />
          {AUDIO_LABEL}
        </div>
      </div>
    </AbsoluteFill>
  );
};
