// Shared DNA for the Fish Audio 4 series (Aug 2026) — "Skilltree gets a voice".
// STYLE: Altari purple (Ahmed's design language) instead of Liam white.
// Source of truth for the tree: real Skilltree screenshots in
// public/fish4/reference/ + the fish 3 approved renders.
// Source of truth for Fish Audio UI/API: real captures in public/fish4/site/.
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

export const ALTARI = {
  // Surfaces (Altari purple world)
  bg: "#1A1A2E",
  bgDeep: "#14142A",
  card: "#2C2C4A",
  card2: "#252542",
  border: "#3D3D60",

  // Brand purples
  primary: "#5B5EC2",
  primaryLight: "#7B7DD6",
  primaryDeep: "#3D2C8D",

  // Text
  heading: "#FFFFFF",
  body: "#A5A7D9",
  faint: "#6E70A8",

  // States
  green: "#4ECD9B",
  red: "#E85D5D",
  amber: "#E8A25B",
} as const;

// Skilltree map palette (kept product-authentic, sits on the Altari bg)
export const TREE = {
  node: "#EDE6D2", // cream constellation nodes
  nodeDim: "#6A7284",
  line: "#3D3D60", // Altari border tone for links
  dotted: "#4A4A72",
  cream: "#F4EDDC",
  muted: "#A5A7D9",
  // Ahmed's voice at the center node = warm amber (distinct from the system purple)
  orb: "#E8A25B",
  orbLite: "#F2C88F",
} as const;

// Fish Audio brand (from fish.audio site)
export const FISH = {
  logoLight: "fish-audio/logo-light.png", // white wordmark for dark bg
  logoDark: "fish-audio/logo-dark.png",
  orange: "#FF4F00", // fish.audio accent (Upgrade/brand pops)
} as const;

// REAL strings — captured from fish.audio on 2026-08-20. Do not invent.
export const API = {
  endpoint: "https://api.fish.audio/v1/tts",
  model: "s2.1-pro-free",
  // exact one-call curl from fish.audio/developers (public/fish4/site/site-developers-curl.png)
  curl: [
    "curl -X POST \\",
    "  https://api.fish.audio/v1/tts \\",
    '  -H "Authorization: Bearer $FISH_API_KEY" \\',
    '  -H "Content-Type: application/json" \\',
    '  -H "model: s2.1-pro-free" \\',
    "  -d '{\"text\": \"Hello! Welcome to Fish Audio.\"}' \\",
    "  --output welcome.mp3",
  ],
  voiceDesignEndpoint: "https://api.fish.audio/v1/voice-design",
  voiceDesignModel: "voice-design-1",
} as const;

// Emotion-tag inputs for the three VOICE lines (from BRIEF-KEY-POINTS.md —
// S2.1 Pro open-domain descriptive tags; these are PRODUCT INPUT text, allowed
// on screen because they demo the feature, not the narration).
export const VOICE_INPUTS = {
  center: "[warm][calm] Two proposals are sitting unsent.",
  deals: "[calm][confident] Harvey. It's been open since Tuesday.",
  ops: "[dry][amused] Onboarding's fine. Your books aren't.",
} as const;

// Required on every audio demo (brand feedback #2)
export const AUDIO_LABEL = "Voice generated by Fish Audio";

// Numbers cleared for use (creative brief)
export const NUMBERS = {
  blindTestRank: "#1",
  bradleyTerry: "3.07",
  languages: 83,
  ttfaMs: 70,
  tokensPerSec: "8,000+",
} as const;

// Springs (Liam skill presets)
export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule).
export const safePadX = (width: number) => Math.round(width * 0.05);

// Altari 64px grid backdrop opacity (keep subtle under the starfield)
export const GRID_SIZE = 64;
export const GRID_LINE = "rgba(91, 94, 194, 0.07)";
