// Shared Runable-interface DNA for the Ahmed x Runable carousel reel (Aug 2026).
// Every value below was SAMPLED FROM THE LIVE APP via getComputedStyle on
// runable.com while logged in — not guessed. Real screenshots that back it up
// live in public/runable/reference/.
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

export const RN = {
  // Surfaces — Runable is a WARM near-white app, not dark.
  bg: "#FEFDFB", // body background (rgb 254,253,251)
  panel: "#F4F1EE", // sidebar / raised panel
  hover: "#F3EFEB", // hover + inset rows
  card: "#FFFFFF", // floating white card on the warm ground
  ink: "#111111", // black buttons (Save, submit arrow)

  // Text
  text: "#060606", // primary (rgb 6,6,6)
  textWarm: "#3D2E24", // active pill label (rgb 61,46,36)
  muted: "#6B5A50", // inactive label (rgb 107,90,80)

  // Lines — Runable uses a hairline black alpha, never a grey hex.
  border: "rgba(0,0,0,0.05)",
  borderStrong: "rgba(0,0,0,0.10)",

  // Accents (the only saturated colors in the whole product)
  amber: "#DE9B4A", // credit pill / gold — the hero accent
  amberSoft: "rgba(222,155,74,0.12)",
  cyan: "#00B7CA", // active feature chip (e.g. Carousels)
  cyanSoft: "rgba(0,183,202,0.10)",
  green: "#1DA25A", // enabled / notify dot
} as const;

// Runable ships its own grotesk. Keep the real name first, fall back safely.
export const FONT_SANS =
  'IDGrotesk, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';
export const FONT_MONO =
  '"SFMono-Regular", ui-monospace, Menlo, Consolas, monospace';

// Springs (Liam skill presets)
export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule).
export const safePadX = (width: number) => Math.round(width * 0.05);

// REAL strings from the product. Do not invent UI copy — if it is not here,
// go look at the screenshots in public/runable/reference/.
export const UI = {
  heading: "What needs to be done?",
  placeholder: "Describe what you want Runable to build...",
  modeAgent: "Agent",
  modeAsk: "Ask",
  model: "Auto",
  plan: "Plan",
  featuresLabel: "Features in Agent mode",
  features: [
    "Websites",
    "Slides",
    "Report",
    "Sheets",
    "Workflows",
    "Apps",
    "Video",
    "Image",
    "Audio",
    "Carousels",
  ],
  nav: ["New task", "Artifacts", "Flow", "Claw", "Meet", "Customize"],
  credits: "1.5k",
  plan_free: "Free plan",

  // The five clarifying questions, verbatim from the real run.
  questions: [
    "Format / aspect ratio for the carousel?",
    "How many pages?",
    "Tone / vibe?",
    "Brand colors, fonts, handle/logo?",
    "Any CTA on the last slide?",
  ],
  qCounter: (n: number) => `Question ${n} of 5`,
  answerPlaceholder: "Type your answer",
  approve: "Approve Plan",
  approvePrompt: "Ready to approve this plan?",

  // Scheduling dialog — the [0:36] beat.
  schedule: {
    title: "Schedule Task",
    instructionsLabel: "Instructions",
    instructionsPlaceholder:
      "e.g. Review my calendar and email me a plan for the day",
    scheduleLabel: "Schedule",
    timeLabel: "Time",
    options: ["Once", "Daily", "Every weekday", "Weekly", "Monthly"],
    notifyLabel: "Notify me on",
    notify: ["Email", "Mobile App"],
    save: "Save",
    cancel: "Cancel",
    tz: "GMT+2",
  },

  // Personalization surface (memory / brand defaults).
  memory: {
    title: "Personalization",
    line: "Memories help Runable remember your preferences.",
    add: "Add a memory",
    sections: ["Your Profile", "Your Memories", "Design System", "Voices"],
  },
} as const;

// Palette of Ahmed's exported carousel slides themselves (near-black cards,
// coral/red accents) — sampled from public/runable/carousel/01.png. Used to
// synthesize month-wall cover variants that sit next to the real exports.
export const SLIDE = {
  bg: "#161618",
  panel: "#1E1E21",
  border: "rgba(255,255,255,0.08)",
  heading: "#F5F4F2",
  mutedText: "rgba(245,244,242,0.55)",
  coral: "#E86B44",
  red: "#EF4B52",
  coralGlow: "rgba(232,107,68,0.4)",
  dot: "rgba(255,255,255,0.05)",
} as const;

// Ahmed's finished carousel, exported at 1080x1350 — staticFile paths.
// Use these for the "ten slides, ready to post" beat. 10 real slides.
export const CAROUSEL_SLIDES = Array.from(
  { length: 10 },
  (_, i) => `runable/carousel/${String(i + 1).padStart(2, "0")}.png`,
);

// Real interface screenshots for fragment insets.
export const SHOTS = {
  home: "runable/reference/01-new-task-home.png",
  composerTyped: "runable/reference/compose-02-idea-typed.png",
  question: "runable/reference/q-2.png",
  questionTone: "runable/reference/qa-3.png",
  questionBrand: "runable/reference/qa-4.png",
  approvePlan: "runable/reference/done-01-chat.png",
  scheduleDialog: "runable/reference/schedule-02-dialog.png",
  scheduleRecurrence: "runable/reference/schedule-04-recurrence.png",
  scheduleDaily: "runable/reference/schedule-05-daily-final.png",
  memory: "runable/reference/customize-memory.png",
  building: "runable/reference/build-01.png",
} as const;

// ===========================================================================
// ALTARI — Ahmed's LOCKED brand design language (@alassafi.ai).
// Source of truth: ~/Work files/CREATORS/Ahmed/Skill files/remotion ahmed/
// altari-remotion/SKILL.md "Design tokens". Never hard-code hex outside this file.
//
// THIS IS THE WORLD. Every composition's root background is ALTARI.bg — the
// deep purple ground — NOT Runable's cream. Runable's real product UI still
// renders in its authentic cream/white, floating as light panels ON the purple.
// ===========================================================================

export const ALTARI = {
  bg: "#1A1A2E", // default canvas — the purple ground
  bgAlt: "#242442", // stat tile bg
  card: "#2C2C4A", // generic card bg (NOT for real Runable UI panels)
  border: "#3D3D60", // all card borders
  heading: "#FFFFFF", // headlines, stat numerals
  body: "#A5A7D9", // subheads, labels, body — lavender, never grey
  primary: "#5B5EC2", // glow accents, dot indicators
  primaryLight: "#7B7DD6", // accent text, CTA card borders
  primaryDeep: "#3D2C8D", // gradient bottom
  terminal: "rgba(13,13,20,0.92)", // terminal panels
  stampRed: "#FF6B8A",
  stampGreen: "#10B981",
  onlineGreen: "#4ADE80",
} as const;

export const ALTARI_GRADIENT = {
  cta: "linear-gradient(135deg, #3D2C8D 0%, #5B5EC2 100%)",
  process: "linear-gradient(145deg, #5C5EC3, #3D2C8D)",
} as const;

// Grid overlay is ALWAYS present: 64x64 on backdrops, 24x24 on cards.
export const ALTARI_GRID = {
  backdrop: 64,
  card: 24,
} as const;

// Altari type stack. Three fonts only — never monospace, even for code-y text
// (use tabular numerals instead).
export const ALTARI_FONT = {
  heading:
    '"SF Pro Display", -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif',
  body: 'Manrope, -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif',
  accent: '"Instrument Serif", Georgia, "Times New Roman", serif', // italic, for numbers/stats
} as const;
