/**
 * Teamily shared style kit — Paper Liam × the REAL Teamily AI app.
 *
 * Sourced 2026-08-16 from the LIVE, SIGNED-IN app at teamily.ai/chat via
 * Playwright over CDP — not the marketing site. The palette below is not
 * pixel-sampled, it is Teamily's own CSS custom-property design system read
 * straight off :root:
 *
 *   --brand-50 #EBFBF3  --brand-100 #D2F7E4  --brand-200 #C0F9C3
 *   --brand-300 #79E3AE --brand-400 #00C951  --brand-500 #00B549
 *   --brand-600 #00A141 --brand-700 #008D39  --brand-800 #007931
 *   --bg-main #FFF  --bg-subtle #F1F5F9  --bg-surface #F8FAFC
 *   --bg-main-black #0F172A
 *   --border-main #E2E8F0  --border-subtle #F1F5F9  --border-brand #00B549
 *   --color-text-muted #94A3B8
 *   --shadow-chat-bubble 0px 2px 10px #0000000d
 *   --shadow-md 0px 4px 8px -2px #1018281a, 0px 2px 4px -2px #1018280f
 *   --shadow-modal 0px 32px 120px #00000026
 *   --radius-sm 8 / md 12 / lg 16 / xl 24 / 2xl 32 / 3xl 40
 *   --font-sans Lato   --font-fira-code Fira Code
 *
 * Real app structure (see public/teamily/app/*.png):
 *   icon rail  → Chat · Agents · Automations · Discover · Explore · Memory · Me
 *   list column→ search + "+", conversation rows, ACTIVE ROW = soft green pill
 *   chat pane  → doodle wallpaper (real asset chat-bg.webp), centred system
 *                lines with agent names in green, agent messages as
 *                [avatar + name] above a white bubble, composer with
 *                + / wrench / plug · "Instant ⌄" · icons · round green button
 *                (mic when empty, paper-plane once you type)
 *
 * The WORLD background stays Liam's warm paper (#F5F1EC) per Victor's
 * standing white-paper default; the Teamily app surfaces sit on top of it.
 *
 * READ-ONLY for builder agents: import tokens and components, build your own
 * layout in your own comp file. Do not edit this file from a part build.
 */
import React from "react";
import { Img, staticFile, interpolate, useCurrentFrame } from "remotion";
import { loadFont as loadLato } from "@remotion/google-fonts/Lato";

// Camera rig, paper world, cursor, typewriter, count-up, safe margins — the
// shared Liam infrastructure. Re-exported so parts import from ONE place.
export {
  useCam,
  PaperWorld,
  PaperBase,
  Cursor,
  useTypewriter,
  useCountUp,
  useEnter,
  tabular,
  fmt,
  safePadX,
  innerW,
  SPRINGS,
  EASE,
  MONO,
} from "../openseo/kit";
export type { Cam } from "../openseo/kit";

const { fontFamily: latoFamily } = loadLato();

/** Teamily's real product font. */
export const FONT = latoFamily;

// ---------------------------------------------------------------------------
// Palette — Teamily's own design tokens
// ---------------------------------------------------------------------------

export const T = {
  /** World background — Liam warm paper. App surfaces sit on top. */
  paper: "#F5F1EC",
  paperWarm: "#EEE8DE",
  /** Hairline for app cards sitting on paper. */
  paperLine: "#E5DED3",

  /** Teamily surfaces. */
  card: "#FFFFFF",
  bgMain: "#FFFFFF",
  bgSubtle: "#F1F5F9",
  bgSurface: "#F8FAFC",
  bgBlack: "#0F172A",

  /** Text. */
  ink: "#0B121E",
  ink2: "#1E293B",
  slate: "#6A7282",
  muted: "#94A3B8",

  /** Lines. */
  line: "#E2E8F0",
  lineSoft: "#F1F5F9",

  /** Brand ramp — verbatim from --brand-*. */
  brand50: "#EBFBF3",
  brand100: "#D2F7E4",
  brand200: "#C0F9C3",
  brand300: "#79E3AE",
  brand400: "#00C951",
  brand500: "#00B549",
  brand600: "#00A141",
  brand700: "#008D39",
  brand800: "#007931",

  /** Convenience aliases. */
  green: "#00C951",
  greenDeep: "#00B549",
  greenText: "#008D39",
  greenTint: "#EBFBF3",
  greenLine: "#C0F9C3",

  /** Old-way / inert state (used sparingly, never neon). */
  grey: "#A8AFBA",
  greySoft: "#EDEFF3",
  red: "#DC2626",
  redSoft: "rgba(220,38,38,0.08)",
  amber: "#B45309",
  amberSoft: "#FEF3C7",

  /** Dark surfaces INSIDE cards only (never full-frame). */
  term: "#1B1A18",
  termBar: "#252320",
  termText: "#E8E4DE",
  termMuted: "#8C877E",
} as const;

/** Teamily's own radius scale. */
export const R = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 40,
  full: 9999,
} as const;

/** Teamily's own shadow scale. */
export const SHADOW = {
  bubble: "0px 2px 10px rgba(0,0,0,0.05)",
  subtle: "0px 1px 2px rgba(16,24,40,0.05)",
  md: "0px 4px 8px -2px rgba(16,24,40,0.10), 0px 2px 4px -2px rgba(16,24,40,0.06)",
  lg: "0px 12px 16px -4px rgba(16,24,40,0.08), 0px 4px 6px -2px rgba(16,24,40,0.03)",
  xl: "0px 20px 24px -4px rgba(16,24,40,0.08), 0px 8px 8px -4px rgba(16,24,40,0.03)",
  modal: "0px 32px 120px rgba(0,0,0,0.15)",
  /** App window floating on paper. */
  window: "0 28px 70px rgba(25,23,20,0.12)",
} as const;

// ---------------------------------------------------------------------------
// Assets — all real, pulled from the live app / teamily-storage CDN
// ---------------------------------------------------------------------------

export const TA = {
  /** Teamily wordmark lockup (green tile + "Teamily AI"), 600×124. */
  logo: "teamily/teamily-logo.png",
  /** Square app mark. */
  mark: "teamily/teamily-mark.webp",
  /** THE REAL chat wallpaper — pale doodle line-art behind every thread. */
  chatBg: "teamily/chat-bg.webp",
  /** Signed-in app captures. These are the visual authority. */
  app: {
    chatHome: "teamily/app/chat-home.png",
    chatGroup: "teamily/app/chat-group.png",
    mentionPicker: "teamily/app/mention-picker.png",
    automations: "teamily/app/automations.png",
    memory: "teamily/app/memory.png",
    agents: "teamily/app/agents.png",
    feedCreations: "teamily/app/feed-creations.png",
  },
  /** Marketing-site captures — secondary reference only. */
  site: {
    feed: "teamily/reference/feed.png",
    messenger: "teamily/reference/messenger.png",
    studioCard: "teamily/reference/studio-card.png",
    hero: "teamily/reference/hero.png",
  },
} as const;

/** Path to a real agent avatar PNG (256×256, pastel circle baked in). */
export const agentSrc = (file: string) => `teamily/avatars/${file}`;

// ---------------------------------------------------------------------------
// Real agents — name + avatar file, straight off the live app.
// 163 avatars in public/teamily/avatars/ (manifest.json has every real
// name + real description). Never invent an agent.
// ---------------------------------------------------------------------------

export type Agent = { name: string; file: string };

export const AG = {
  trendResearcher: { name: "Trend Researcher", file: "product-trend-researcher.png" },
  contentCreator: { name: "Content Creator", file: "marketing-content-creator.png" },
  frontendDev: { name: "Frontend Developer", file: "engineering-frontend-developer.png" },
  docGenerator: { name: "Document Generator", file: "specialized-document-generator.png" },
  uxResearcher: { name: "UX Researcher", file: "design-ux-researcher.png" },
  productManager: { name: "Product Manager", file: "product-manager.png" },
  growthHacker: { name: "Growth Hacker", file: "marketing-growth-hacker.png" },
  socialStrategist: { name: "Social Media Strategist", file: "marketing-social-media-strategist.png" },
  uiDesigner: { name: "UI Designer", file: "design-ui-designer.png" },
  brandGuardian: { name: "Brand Guardian", file: "design-brand-guardian.png" },
  seoSpecialist: { name: "SEO Specialist", file: "marketing-seo-specialist.png" },
  rapidPrototyper: { name: "Rapid Prototyper", file: "engineering-rapid-prototyper.png" },
  codeReviewer: { name: "Code Reviewer", file: "engineering-code-reviewer.png" },
  gitWorkflowMaster: { name: "Git Workflow Master", file: "engineering-git-workflow-master.png" },
  seniorDeveloper: { name: "Senior Developer", file: "engineering-senior-developer.png" },
  dataEngineer: { name: "Data Engineer", file: "engineering-data-engineer.png" },
  financialAnalyst: { name: "Financial Analyst", file: "finance-financial-analyst.png" },
  pipelineAnalyst: { name: "Pipeline Analyst", file: "sales-pipeline-analyst.png" },
  chiefOfStaff: { name: "Chief of Staff", file: "specialized-chief-of-staff.png" },
  visualStoryteller: { name: "Visual Storyteller", file: "design-visual-storyteller.png" },
  technicalWriter: { name: "Technical Writer", file: "engineering-technical-writer.png" },
  projectShepherd: { name: "Project Shepherd", file: "project-management-project-shepherd.png" },
  psychologist: { name: "Psychologist", file: "academic-psychologist.png" },
  historian: { name: "Historian", file: "academic-historian.png" },
  backendArchitect: { name: "Backend Architect", file: "engineering-backend-architect.png" },
  devopsAutomator: { name: "DevOps Automator", file: "engineering-devops-automator.png" },
  emailStrategist: { name: "Email Marketing Strategist", file: "marketing-email-strategist.png" },
  mcpBuilder: { name: "MCP Builder", file: "specialized-mcp-builder.png" },
  businessStrategist: { name: "Business Strategist", file: "business-strategist.png" },
  customerSuccess: { name: "Customer Success Manager", file: "customer-success-manager.png" },
  incidentCommander: { name: "Incident Response Commander", file: "engineering-incident-response-commander.png" },
  databaseOptimizer: { name: "Database Optimizer", file: "engineering-database-optimizer.png" },
} as const satisfies Record<string, Agent>;

/** A broad pool for feed grids — real names, real avatars, no invention. */
export const FEED_POOL: Agent[] = [
  AG.trendResearcher, AG.contentCreator, AG.frontendDev, AG.docGenerator,
  AG.uxResearcher, AG.productManager, AG.growthHacker, AG.socialStrategist,
  AG.uiDesigner, AG.brandGuardian, AG.seoSpecialist, AG.rapidPrototyper,
  AG.codeReviewer, AG.dataEngineer, AG.financialAnalyst, AG.pipelineAnalyst,
  AG.chiefOfStaff, AG.visualStoryteller, AG.technicalWriter, AG.projectShepherd,
  AG.psychologist, AG.historian, AG.backendArchitect, AG.devopsAutomator,
  AG.emailStrategist, AG.mcpBuilder, AG.businessStrategist, AG.customerSuccess,
  AG.gitWorkflowMaster, AG.seniorDeveloper, AG.incidentCommander, AG.databaseOptimizer,
];

/**
 * REAL automation presets, verbatim from the app's Automations → Work tab.
 * Two of these are exactly the script's part-7 examples.
 */
export const AUTOMATIONS = [
  { title: "Meeting reminder + prep", desc: "Remind me before a meeting and pull the latest materials" },
  { title: "Daily work brief", desc: "Every morning, summarize progress, to-dos and risks" },
  { title: "Competitor / industry monitor", desc: "Keep watching and ping me when something changes" },
  { title: "Expert group research", desc: "Spin up an expert agent squad to investigate a question" },
  { title: "Make a deck / report", desc: "Produce a presentation or report I can publish" },
  { title: "Build a webpage / tool", desc: "Build a small web page or utility for a purpose" },
  { title: "Break down & assign tasks", desc: "Split a project into sub-tasks and track owners" },
  { title: "Reply in my voice", desc: "Let my AI Twin draft replies; I confirm anything risky" },
  { title: "Investment / market research", desc: "AI + finance experts study a strategy together" },
  { title: "Drive a goal (deck, launch…)", desc: "Break a big goal into milestones and keep pushing" },
  { title: "Inbox triage & follow-ups", desc: "Summarize messages and surface what needs a reply" },
  { title: "Cross-timezone relay", desc: "Queue messages and log decisions across timezones" },
] as const;

/** Real Discover → Feeds filter chips. */
export const FEED_FILTERS = [
  "All", "Webpage", "Mini Game", "Image", "Music", "Slides",
  "Video", "3D Artifact", "Short Drama", "Article", "Tutorials",
] as const;

/** Real Agents → category chips. */
export const AGENT_CATEGORIES = [
  "All", "Academic", "Design", "Engineering", "Finance", "Game Development",
  "Marketing", "Paid Media", "Product", "Project Management", "Sales",
  "Security", "Spatial Computing", "Specialized", "Support", "Testing",
] as const;

// ---------------------------------------------------------------------------
// Brand marks
// ---------------------------------------------------------------------------

/** Teamily logo lockup (real PNG, 600×124 → aspect 4.839). */
export const TeamilyLockup: React.FC<{ width: number; style?: React.CSSProperties }> = ({
  width,
  style,
}) => (
  <Img
    src={staticFile(TA.logo)}
    style={{ width, height: width / 4.839, objectFit: "contain", display: "block", ...style }}
  />
);

/** Square Teamily app mark (rounded tile). */
export const TeamilyMark: React.FC<{ size: number; style?: React.CSSProperties }> = ({
  size,
  style,
}) => (
  <Img
    src={staticFile(TA.mark)}
    style={{ width: size, height: size, borderRadius: size * 0.28, display: "block", ...style }}
  />
);

/** Real agent avatar — circular crop; the pastel disc is baked into the PNG. */
export const AgentAvatar: React.FC<{
  agent: Agent;
  size: number;
  ring?: boolean;
  style?: React.CSSProperties;
}> = ({ agent, size, ring = false, style }) => (
  <Img
    src={staticFile(agentSrc(agent.file))}
    style={{
      width: size,
      height: size,
      borderRadius: R.full,
      display: "block",
      objectFit: "cover",
      border: ring ? `${Math.max(2, size * 0.045)}px solid ${T.green}` : "none",
      ...style,
    }}
  />
);

/**
 * Human participant. We have no real photos and must not fabricate a
 * real-looking person — the app shows humans as a disc, so use an initial.
 */
export const HumanAvatar: React.FC<{
  initial: string;
  size: number;
  tint?: string;
  style?: React.CSSProperties;
}> = ({ initial, size, tint = "#D7E3F4", style }) => (
  <div
    style={{
      width: size,
      height: size,
      borderRadius: R.full,
      background: tint,
      color: "#3E4C5E",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: FONT,
      fontWeight: 700,
      fontSize: size * 0.44,
      flexShrink: 0,
      ...style,
    }}
  >
    {initial}
  </div>
);

/** 2×2 avatar stack — how the app renders a group conversation's icon. */
export const AvatarStack: React.FC<{ agents: Agent[]; size: number }> = ({ agents, size }) => {
  const s = size * 0.56;
  const gap = size - s;
  return (
    <div style={{ position: "relative", width: size, height: size, flexShrink: 0 }}>
      {agents.slice(0, 4).map((a, i) => (
        <AgentAvatar
          key={a.file + i}
          agent={a}
          size={s}
          style={{
            position: "absolute",
            left: (i % 2) * gap,
            top: Math.floor(i / 2) * gap,
            border: `${Math.max(1.5, size * 0.02)}px solid ${T.card}`,
          }}
        />
      ))}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Generic surfaces
// ---------------------------------------------------------------------------

/** A white Teamily card floating on paper. */
export const TCard: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  r?: number;
  enter?: number;
  accent?: boolean;
  lift?: number;
  shadow?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}> = ({ x, y, w, h, r = R.xl, enter = 1, accent = false, lift = 26, shadow, style, children }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      height: h,
      borderRadius: r,
      background: T.card,
      border: `1.5px solid ${accent ? T.greenLine : T.line}`,
      boxShadow: shadow ?? SHADOW.lg,
      opacity: enter,
      transform: `translateY(${(1 - enter) * lift}px)`,
      boxSizing: "border-box",
      ...style,
    }}
  >
    {children}
  </div>
);

/** Pill chip — matches the real category / filter chips. */
export const TChip: React.FC<{
  label: string;
  tone?: "neutral" | "green" | "solid" | "grey" | "amber";
  size?: number;
  style?: React.CSSProperties;
}> = ({ label, tone = "neutral", size = 26, style }) => {
  const tones = {
    neutral: { bg: T.card, fg: T.ink, bd: T.line },
    green: { bg: T.greenTint, fg: T.greenText, bd: T.greenLine },
    solid: { bg: T.green, fg: "#FFFFFF", bd: T.green },
    grey: { bg: T.greySoft, fg: T.grey, bd: T.lineSoft },
    amber: { bg: T.amberSoft, fg: T.amber, bd: "#FDE68A" },
  }[tone];
  return (
    <div
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
        padding: `${Math.round(size * 0.44)}px ${Math.round(size * 0.86)}px`,
        borderRadius: R.full,
        background: tones.bg,
        border: `1.5px solid ${tones.bd}`,
        color: tones.fg,
        fontFamily: FONT,
        fontSize: size,
        fontWeight: 600,
        whiteSpace: "nowrap",
        ...style,
      }}
    >
      {label}
    </div>
  );
};

/** Teamily's green pill button ("Chat", "Create My Own Agent", "Open Studio"). */
export const TButton: React.FC<{
  label: string;
  size?: number;
  /** 0..1 press depth for click beats. */
  press?: number;
  icon?: React.ReactNode;
  style?: React.CSSProperties;
}> = ({ label, size = 28, press = 0, icon, style }) => (
  <div
    style={{
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      padding: `${Math.round(size * 0.5)}px ${Math.round(size * 1.05)}px`,
      borderRadius: R.full,
      background: press > 0.5 ? T.brand500 : T.brand400,
      color: "#FFFFFF",
      fontFamily: FONT,
      fontSize: size,
      fontWeight: 700,
      whiteSpace: "nowrap",
      transform: `scale(${1 - press * 0.05})`,
      boxShadow: `0 ${8 - press * 5}px ${20 - press * 10}px rgba(0,201,81,0.26)`,
      ...style,
    }}
  >
    {icon}
    {label}
  </div>
);

// ---------------------------------------------------------------------------
// App chrome — the real signed-in Teamily layout
// ---------------------------------------------------------------------------

export const RAIL_ITEMS = [
  "Chat", "Agents", "Automations", "Discover", "Explore", "Memory", "Me",
] as const;
export type RailItem = (typeof RAIL_ITEMS)[number];

/** The real left icon rail: green Teamily tile on top, then labelled glyphs. */
export const IconRail: React.FC<{
  w: number;
  h: number;
  active?: RailItem;
  scale?: number;
}> = ({ w, h, active = "Chat", scale = 1 }) => (
  <div
    style={{
      position: "absolute",
      left: 0,
      top: 0,
      width: w,
      height: h,
      background: T.card,
      borderRight: `1.5px solid ${T.lineSoft}`,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      paddingTop: 26 * scale,
      gap: 24 * scale,
      boxSizing: "border-box",
    }}
  >
    <TeamilyMark size={56 * scale} />
    <div style={{ height: 10 * scale }} />
    {RAIL_ITEMS.map((label) => {
      const on = label === active;
      return (
        <div
          key={label}
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 5 * scale,
            opacity: on ? 1 : 0.55,
          }}
        >
          <div
            style={{
              width: 30 * scale,
              height: 30 * scale,
              borderRadius: 9 * scale,
              border: `2.2px solid ${on ? T.ink : T.muted}`,
            }}
          />
          <div
            style={{
              fontFamily: FONT,
              fontSize: 15 * scale,
              fontWeight: on ? 700 : 500,
              color: on ? T.ink : T.muted,
            }}
          >
            {label}
          </div>
        </div>
      );
    })}
  </div>
);

/**
 * A conversation row in the list column.
 * The ACTIVE row is a soft green rounded pill — that is the real app's
 * selected state (not a white card with a green bar).
 */
export const ChatRow: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  agent?: Agent;
  stack?: Agent[];
  title: string;
  time?: string;
  preview: string;
  active?: boolean;
  enter?: number;
  /** Renders the preview's leading names in brand green, like the app does. */
  greenNames?: string;
  style?: React.CSSProperties;
}> = ({
  x, y, w, h = 112, agent, stack, title, time, preview,
  active = false, enter = 1, greenNames, style,
}) => {
  const av = 64;
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        width: w,
        height: h,
        display: "flex",
        alignItems: "center",
        gap: 18,
        padding: "0 22px",
        borderRadius: R.xl,
        background: active ? T.greenTint : "transparent",
        border: `1.5px solid ${active ? T.greenLine : "transparent"}`,
        opacity: enter,
        transform: `translateY(${(1 - enter) * 12}px)`,
        boxSizing: "border-box",
        ...style,
      }}
    >
      {stack ? (
        <AvatarStack agents={stack} size={av} />
      ) : agent ? (
        <AgentAvatar agent={agent} size={av} style={{ flexShrink: 0 }} />
      ) : (
        <div
          style={{
            width: av,
            height: av,
            borderRadius: R.full,
            background: T.bgSubtle,
            flexShrink: 0,
          }}
        />
      )}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 12 }}>
          <div
            style={{
              fontFamily: FONT,
              fontSize: 27,
              fontWeight: 600,
              color: T.ink,
              whiteSpace: "nowrap",
              overflow: "hidden",
              textOverflow: "ellipsis",
            }}
          >
            {title}
          </div>
          {time ? (
            <div
              style={{
                marginLeft: "auto",
                fontFamily: FONT,
                fontSize: 20,
                color: T.muted,
                flexShrink: 0,
              }}
            >
              {time}
            </div>
          ) : null}
        </div>
        <div
          style={{
            fontFamily: FONT,
            fontSize: 22,
            color: T.muted,
            marginTop: 5,
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
          }}
        >
          {greenNames ? <span style={{ color: T.greenText }}>{greenNames}</span> : null}
          {greenNames ? " " : ""}
          {preview}
        </div>
      </div>
    </div>
  );
};

/** Chat pane background: the REAL doodle wallpaper asset. */
export const ChatWallpaper: React.FC<{
  x: number;
  y: number;
  w: number;
  h: number;
  opacity?: number;
  r?: number;
}> = ({ x, y, w, h, opacity = 1, r = 0 }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      height: h,
      overflow: "hidden",
      borderRadius: r,
      background: "#F4FAF6",
    }}
  >
    <Img
      src={staticFile(TA.chatBg)}
      style={{
        width: "100%",
        height: "100%",
        objectFit: "cover",
        opacity,
        display: "block",
      }}
    />
  </div>
);

/** Group/DM header: avatar (or stack), title, optional badge, member count. */
export const ChatHeader: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  title: string;
  sub?: string;
  badge?: string;
  agent?: Agent;
  stack?: Agent[];
  enter?: number;
}> = ({ x, y, w, h = 116, title, sub, badge, agent, stack, enter = 1 }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      height: h,
      background: T.card,
      borderBottom: `1.5px solid ${T.lineSoft}`,
      display: "flex",
      alignItems: "center",
      gap: 18,
      padding: "0 28px",
      opacity: enter,
      boxSizing: "border-box",
    }}
  >
    {stack ? <AvatarStack agents={stack} size={62} /> : agent ? <AgentAvatar agent={agent} size={62} /> : null}
    <div style={{ minWidth: 0 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
        <div style={{ fontFamily: FONT, fontSize: 30, fontWeight: 700, color: T.ink }}>{title}</div>
        {badge ? <TChip label={badge} tone="amber" size={16} /> : null}
      </div>
      {sub ? (
        <div style={{ fontFamily: FONT, fontSize: 21, color: T.muted, marginTop: 3 }}>{sub}</div>
      ) : null}
    </div>
  </div>
);

/** Centred system line ("You created the group", "X were invited…"). */
export const SystemLine: React.FC<{
  x: number;
  y: number;
  w: number;
  enter?: number;
  size?: number;
  /** Leading names rendered in brand green, exactly like the app. */
  names?: string;
  children?: React.ReactNode;
}> = ({ x, y, w, enter = 1, size = 21, names, children }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      textAlign: "center",
      fontFamily: FONT,
      fontSize: size,
      color: T.muted,
      opacity: enter,
    }}
  >
    {names ? <span style={{ color: T.greenText }}>{names}</span> : null}
    {names ? " " : ""}
    {children}
  </div>
);

/**
 * An agent message: circular avatar + bold name on its own line, then a
 * white bubble beneath. This is the app's real layout for non-you senders.
 */
export const AgentMsg: React.FC<{
  x: number;
  y: number;
  w: number;
  agent: Agent;
  /** Override the displayed name (defaults to the agent's real name). */
  name?: string;
  enter?: number;
  size?: number;
  pad?: number;
  children?: React.ReactNode;
  style?: React.CSSProperties;
}> = ({ x, y, w, agent, name, enter = 1, size = 27, pad = 26, children, style }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      opacity: enter,
      transform: `translateY(${(1 - enter) * 16}px)`,
      ...style,
    }}
  >
    <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 12 }}>
      <AgentAvatar agent={agent} size={48} />
      <div style={{ fontFamily: FONT, fontSize: 26, fontWeight: 700, color: T.ink }}>
        {name ?? agent.name}
      </div>
    </div>
    <div
      style={{
        marginLeft: 62,
        background: T.card,
        borderRadius: R.xl,
        boxShadow: SHADOW.bubble,
        padding: pad,
        fontFamily: FONT,
        fontSize: size,
        lineHeight: 1.45,
        color: T.ink,
      }}
    >
      {children}
    </div>
  </div>
);

/** Your own message — brand green bubble, right-aligned. */
export const MeMsg: React.FC<{
  /** Right edge of the bubble. */
  right: number;
  y: number;
  maxW: number;
  enter?: number;
  size?: number;
  children?: React.ReactNode;
  style?: React.CSSProperties;
}> = ({ right, y, maxW, enter = 1, size = 27, children, style }) => (
  <div
    style={{
      position: "absolute",
      right,
      top: y,
      maxWidth: maxW,
      padding: "20px 26px",
      borderRadius: R.xl,
      background: T.brand400,
      color: "#FFFFFF",
      fontFamily: FONT,
      fontSize: size,
      lineHeight: 1.45,
      opacity: enter,
      transform: `translateY(${(1 - enter) * 14}px)`,
      boxShadow: "0 6px 18px rgba(0,201,81,0.22)",
      ...style,
    }}
  >
    {children}
  </div>
);

/**
 * Composer action glyphs. Drawn as SVG, never emoji — headless Chrome renders
 * emoji as heavy pictographs that read as a dark blob on the green disc.
 */
export const MicGlyph: React.FC<{ size?: number; color?: string }> = ({
  size = 26,
  color = "#FFFFFF",
}) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <rect x="9" y="2.5" width="6" height="11" rx="3" fill={color} />
    <path
      d="M5.5 11a6.5 6.5 0 0 0 13 0"
      stroke={color}
      strokeWidth={2}
      strokeLinecap="round"
      fill="none"
    />
    <path d="M12 17.5V21" stroke={color} strokeWidth={2} strokeLinecap="round" />
  </svg>
);

export const SendGlyph: React.FC<{ size?: number; color?: string }> = ({
  size = 26,
  color = "#FFFFFF",
}) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <path
      d="M3.4 11.3 20 4.2c.7-.3 1.4.4 1.1 1.1l-7.1 16.6c-.3.7-1.3.7-1.5-.1l-1.9-6.3-6.3-1.9c-.8-.2-.8-1.2-.1-1.5Z"
      fill={color}
    />
  </svg>
);

/**
 * The real composer: rounded white bar, "+" / wrench / plug on the left,
 * "Instant ⌄" mode selector, then icons, then the round green action button
 * (mic when empty, paper-plane once there's content).
 */
export const Composer: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  /** Rich content (mention pills + typed text). Plain string also fine. */
  children?: React.ReactNode;
  /** Empty → mic; non-empty → paper-plane. */
  armed?: boolean;
  caret?: boolean;
  focus?: number;
  press?: number;
  enter?: number;
}> = ({ x, y, w, h = 150, children, armed = false, caret = false, focus = 0, press = 0, enter = 1 }) => {
  const frame = useCurrentFrame();
  const blink = interpolate(frame % 30, [0, 14, 15, 29], [1, 1, 0, 0]);
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        width: w,
        height: h,
        borderRadius: R.xxl,
        background: T.card,
        border: `2px solid ${focus > 0.5 ? T.greenLine : T.line}`,
        boxShadow: SHADOW.md,
        opacity: enter,
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "20px 24px 16px",
        boxSizing: "border-box",
      }}
    >
      <div
        style={{
          fontFamily: FONT,
          fontSize: 27,
          color: T.ink,
          lineHeight: 1.4,
          display: "flex",
          flexWrap: "wrap",
          alignItems: "center",
        }}
      >
        {children}
        {caret ? (
          <span
            style={{
              display: "inline-block",
              width: 2.5,
              height: 30,
              background: T.ink,
              opacity: blink,
              marginLeft: 2,
              transform: "translateY(5px)",
            }}
          />
        ) : null}
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
        {["+", "⚙", "⌘"].map((g, i) => (
          <div
            key={i}
            style={{ fontFamily: FONT, fontSize: 26, color: T.muted, width: 28, textAlign: "center" }}
          >
            {g}
          </div>
        ))}
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 16 }}>
          <div style={{ fontFamily: FONT, fontSize: 23, color: T.slate }}>Instant ⌄</div>
          <div
            style={{
              width: 54,
              height: 54,
              borderRadius: R.full,
              background: press > 0.5 ? T.brand500 : T.brand400,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              transform: `scale(${1 - press * 0.08})`,
              boxShadow: "0 6px 16px rgba(0,201,81,0.28)",
            }}
          >
            {armed ? <SendGlyph size={26} /> : <MicGlyph size={26} />}
          </div>
        </div>
      </div>
    </div>
  );
};

/** Green @mention pill as it renders inside the composer / a sent message. */
export const Mention: React.FC<{ name: string; size?: number; onGreen?: boolean }> = ({
  name,
  size = 27,
  onGreen = false,
}) => (
  <span
    style={{
      display: "inline-flex",
      alignItems: "center",
      padding: `${Math.round(size * 0.1)}px ${Math.round(size * 0.36)}px`,
      margin: "0 4px 0 0",
      borderRadius: R.sm,
      background: onGreen ? "rgba(255,255,255,0.22)" : T.greenTint,
      color: onGreen ? "#FFFFFF" : T.greenText,
      fontFamily: FONT,
      fontSize: size,
      fontWeight: 700,
      whiteSpace: "nowrap",
    }}
  >
    @{name}
  </span>
);

/**
 * The real @-mention picker: a floating white panel above the composer with
 * an "Everyone" row, a "Members" label, then avatar + name rows.
 */
export const MentionPicker: React.FC<{
  x: number;
  /** Bottom edge — the panel sits above the composer. */
  bottom: number;
  w: number;
  agents: Agent[];
  /** Index of the row under the cursor. */
  highlight?: number;
  enter?: number;
  showEveryone?: boolean;
}> = ({ x, bottom, w, agents, highlight = -1, enter = 1, showEveryone = true }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      bottom,
      width: w,
      borderRadius: R.xl,
      background: T.card,
      boxShadow: SHADOW.modal,
      border: `1.5px solid ${T.lineSoft}`,
      padding: 14,
      opacity: enter,
      transform: `translateY(${(1 - enter) * 18}px)`,
      boxSizing: "border-box",
    }}
  >
    {showEveryone ? (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 16,
          padding: "16px 18px",
          borderRadius: R.lg,
          background: T.bgSurface,
          marginBottom: 10,
        }}
      >
        <div style={{ fontFamily: FONT, fontSize: 30, color: T.slate, width: 34 }}>@</div>
        <div>
          <div style={{ fontFamily: FONT, fontSize: 27, fontWeight: 600, color: T.ink }}>Everyone</div>
          <div style={{ fontFamily: FONT, fontSize: 20, color: T.muted, marginTop: 2 }}>
            Notify everyone in this group
          </div>
        </div>
      </div>
    ) : null}
    <div
      style={{
        fontFamily: FONT,
        fontSize: 19,
        color: T.muted,
        padding: "6px 18px 10px",
      }}
    >
      Members
    </div>
    {agents.map((a, i) => (
      <div
        key={a.file + i}
        style={{
          display: "flex",
          alignItems: "center",
          gap: 16,
          padding: "13px 18px",
          borderRadius: R.lg,
          background: i === highlight ? T.greenTint : "transparent",
        }}
      >
        <AgentAvatar agent={a} size={44} />
        <div style={{ fontFamily: FONT, fontSize: 27, color: T.ink }}>{a.name}</div>
      </div>
    ))}
  </div>
);

/**
 * An in-chat deliverable/artifact card — the app's studio output:
 * title row + green type badge, a preview body, then the meta strip and
 * the green "Open Studio" action.
 */
export const DeliveryCard: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  title: string;
  badge: string;
  enter?: number;
  meta?: string;
  action?: string;
  press?: number;
  children?: React.ReactNode;
  style?: React.CSSProperties;
}> = ({
  x, y, w, h, title, badge, enter = 1,
  meta = "1 delivery · v1 · Thought for 12s", action = "Open Studio", press = 0, children, style,
}) => (
  <TCard x={x} y={y} w={w} h={h} r={R.xl} enter={enter} shadow={SHADOW.bubble} style={{ overflow: "hidden", ...style }}>
    <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "22px 26px 14px" }}>
      <div
        style={{
          width: 34,
          height: 34,
          borderRadius: R.sm,
          background: T.bgSubtle,
          border: `1.5px solid ${T.line}`,
          flexShrink: 0,
        }}
      />
      <div
        style={{
          fontFamily: FONT,
          fontSize: 26,
          fontWeight: 700,
          color: T.ink,
          whiteSpace: "nowrap",
          overflow: "hidden",
          textOverflow: "ellipsis",
        }}
      >
        {title}
      </div>
      <TChip label={badge} tone="green" size={16} style={{ marginLeft: "auto", flexShrink: 0 }} />
    </div>
    {children}
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "16px 26px 20px",
        fontFamily: FONT,
        fontSize: 19,
        color: T.muted,
      }}
    >
      <span style={{ width: 9, height: 9, borderRadius: R.full, background: T.green, display: "inline-block" }} />
      {meta}
      <TButton label={action} size={19} press={press} style={{ marginLeft: "auto" }} />
    </div>
  </TCard>
);

/** Three-dot "agent is typing" indicator. */
export const Typing: React.FC<{
  x: number;
  y: number;
  enter?: number;
  color?: string;
}> = ({ x, y, enter = 1, color = T.muted }) => {
  const frame = useCurrentFrame();
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        display: "flex",
        alignItems: "center",
        gap: 9,
        padding: "18px 24px",
        borderRadius: R.xl,
        background: T.card,
        boxShadow: SHADOW.bubble,
        opacity: enter,
      }}
    >
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          style={{
            width: 12,
            height: 12,
            borderRadius: R.full,
            background: color,
            opacity: interpolate((frame + i * 6) % 30, [0, 8, 16, 30], [0.28, 1, 0.28, 0.28]),
          }}
        />
      ))}
    </div>
  );
};

/** Soft green halo — the ONLY glow allowed; marks the live/active node. */
export const GreenHalo: React.FC<{
  cx: number;
  cy: number;
  r: number;
  strength?: number;
}> = ({ cx, cy, r, strength = 1 }) => (
  <div
    style={{
      position: "absolute",
      left: cx - r,
      top: cy - r,
      width: r * 2,
      height: r * 2,
      borderRadius: R.full,
      background: `radial-gradient(circle, rgba(0,201,81,${0.16 * strength}) 0%, rgba(0,201,81,0) 70%)`,
      pointerEvents: "none",
    }}
  />
);

/**
 * A whole Teamily app window floating on paper: rail + list column + chat
 * pane with the real wallpaper. Children are placed in window-local coords.
 */
export const AppWindow: React.FC<{
  x: number;
  y: number;
  w: number;
  h: number;
  railW?: number;
  listW?: number;
  active?: RailItem;
  enter?: number;
  railScale?: number;
  /** Set false to render the pane plain (e.g. Automations / Memory screens). */
  wallpaper?: boolean;
  children?: React.ReactNode;
}> = ({
  x, y, w, h, railW = 132, listW = 396, active = "Chat",
  enter = 1, railScale = 1.35, wallpaper = true, children,
}) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      height: h,
      borderRadius: R.xxl,
      background: T.card,
      boxShadow: SHADOW.window,
      border: `1.5px solid ${T.paperLine}`,
      overflow: "hidden",
      opacity: enter,
      transform: `translateY(${(1 - enter) * 24}px)`,
      boxSizing: "border-box",
    }}
  >
    <IconRail w={railW} h={h} active={active} scale={railScale} />
    <div
      style={{
        position: "absolute",
        left: railW,
        top: 0,
        width: listW,
        height: h,
        background: T.card,
        borderRight: `1.5px solid ${T.lineSoft}`,
      }}
    />
    {wallpaper ? (
      <ChatWallpaper x={railW + listW} y={0} w={w - railW - listW} h={h} />
    ) : (
      <div
        style={{
          position: "absolute",
          left: railW + listW,
          top: 0,
          width: w - railW - listW,
          height: h,
          background: T.bgSurface,
        }}
      />
    )}
    {children}
  </div>
);
