// ===========================================================================
// Bennett x Runable GROW reel (Aug 2026) — shared series DNA.
//
// THE WORLD IS MERYDIAN DARK. Bennett runs the AI agency Merydian
// (merydian.ai). Every composition's root background is MRD.bg — the near-black
// ground — with Merydian's spring green as the only saturated accent.
// Runable's real product UI keeps its OWN authentic warm near-white and floats
// as light panels ON that dark ground. Same structural move Ahmed's ALTARI
// series made, different world.
//
// Liam's SYSTEM (cinematic camera, floating cards, hairlines, staggered
// entrances, hold -> move -> hold) with MERYDIAN's PALETTE. Not Liam white.
//
// Every value below was SAMPLED FROM A REAL SOURCE, not invented:
//   MRD  -> :root custom properties in merydian.ai's compiled stylesheet
//   RN   -> getComputedStyle on the live runable.com app + the official
//           brand page at creatoros.runable.site/brand
// Screenshots backing every claim: public/bgrow/capture/
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.
// ===========================================================================

// ------------------------------------------------------- Merydian dark world
export const MRD = {
  bg: "#0A0A0A", // --background : the ground, every root AbsoluteFill
  bgLift: "#101010", // subtle floor gradient top
  card: "#1A1A1A", // --card : raised surface / secondary CTA
  cardSoft: "#141414",
  hairline: "rgba(255,255,255,0.08)", // card border on dark
  hairlineSoft: "rgba(255,255,255,0.05)",
  text: "#EEEDED", // --foreground : headings
  muted: "#737373", // --accent : body copy, labels
  green: "#00FFAB", // --primary-cta : THE Merydian accent
  greenInk: "#000000", // --primary-cta-text : text ON the green pill
  greenSoft: "rgba(0,255,171,0.12)",
  greenGlow: "rgba(0,255,171,0.34)",
  teal: "#00D5C7", // --background-accent : secondary accent
  tealSoft: "rgba(0,213,199,0.12)",
  // Shadows read as glow on dark, never as drop shadow.
  glow: "0 0 48px rgba(0,255,171,0.20)",
  glowSoft: "0 0 28px rgba(0,255,171,0.12)",
  panelShadow: "0 24px 60px rgba(0,0,0,0.55), 0 2px 8px rgba(0,0,0,0.40)",
} as const;

// The vertical light streaks bleeding from the top are part of Merydian's
// identity (see public/bgrow/merydian/ogimagemerydian.png). Reuse, don't invent.
export const MRD_GRADIENT = {
  ground: "linear-gradient(180deg, #101010 0%, #0A0A0A 55%, #070707 100%)",
  streak:
    "linear-gradient(180deg, rgba(0,255,171,0.14) 0%, rgba(0,255,171,0.00) 62%)",
  cta: "linear-gradient(135deg, #00FFAB 0%, #00D5C7 100%)",
} as const;

// Faint vertical rule grid on the backdrop, like the real site.
export const MRD_GRID = { spacing: 96, color: "rgba(255,255,255,0.035)" } as const;

// ------------------------------------------------------- Runable product UI
// KEEP THE RUNABLE INTERFACE AS IT IS. It renders in its own warm near-white
// on top of the Merydian dark ground. Do not recolor Runable panels green.
export const RN = {
  bg: "#FEFDFB", // Canvas (official brand token)
  panel: "#F4F1EE", // sidebar / raised panel
  hover: "#F3EFEB",
  card: "#FFFFFF",
  ink: "#141414", // Ink (official brand token) — black buttons
  text: "#060606",
  textWarm: "#3D2E24",
  muted: "#6B5A50",
  border: "rgba(0,0,0,0.05)",
  borderStrong: "rgba(0,0,0,0.10)",
  cyan: "#00B9CC", // Runable Cyan — the official accent
  cyanSoft: "rgba(0,185,204,0.10)",
  amber: "#DE9B4A", // credit pill gold
  amberSoft: "rgba(222,155,74,0.12)",
  green: "#1DA25A",
} as const;

// ---------------------------------------------------------------- Typography
// Merydian ships Halant (serif display) + Inter (UI). Runable ships ID Grotesk,
// downloaded from the official brand page into public/bgrow/fonts/.
export const FONT_DISPLAY =
  'Halant, "Times New Roman", Georgia, serif'; // Merydian headings
export const FONT_UI =
  'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';
export const FONT_RUNABLE =
  'IDGrotesk, Inter, ui-sans-serif, -apple-system, Helvetica, Arial, sans-serif';
export const FONT_MONO =
  '"SFMono-Regular", ui-monospace, Menlo, Consolas, monospace';

// Drop this <style> into a comp once to make FONT_RUNABLE resolve to the real
// ID Grotesk TTFs. Call with staticFile from the comp.
export const idGroteskFaces = (staticFile: (p: string) => string) => `
@font-face { font-family: 'IDGrotesk'; font-weight: 300; font-style: normal;
  src: url('${staticFile("bgrow/fonts/IDGrotesk-Light.ttf")}') format('truetype'); }
@font-face { font-family: 'IDGrotesk'; font-weight: 350; font-style: normal;
  src: url('${staticFile("bgrow/fonts/IDGrotesk-Book.ttf")}') format('truetype'); }
@font-face { font-family: 'IDGrotesk'; font-weight: 400; font-style: normal;
  src: url('${staticFile("bgrow/fonts/IDGrotesk-Regular.ttf")}') format('truetype'); }
@font-face { font-family: 'IDGrotesk'; font-weight: 500; font-style: normal;
  src: url('${staticFile("bgrow/fonts/IDGrotesk-Medium.ttf")}') format('truetype'); }
@font-face { font-family: 'IDGrotesk'; font-weight: 700; font-style: normal;
  src: url('${staticFile("bgrow/fonts/IDGrotesk-Bold.ttf")}') format('truetype'); }
`;

// ------------------------------------------------------------------- Motion
export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule: 54px on a 1080 canvas).
export const safePadX = (width: number) => Math.round(width * 0.05);

// ===========================================================================
// REAL UI STRINGS — captured from the live app on Aug 27, 2026 during the
// Grow walkthrough. Do not invent UI copy. If it is not here, go look at
// public/bgrow/capture/.
// ===========================================================================
export const UI = {
  // Top bar
  toggle: ["Build", "Grow"] as const,
  credits: "1.5k",

  // Left sidebar (identical in Build and Grow)
  nav: ["New task", "Artifacts", "Flow", "Claw", "Meet", "Customize"],
  projectsLabel: "Projects",
  projectsEmpty: "No projects yet",
  historyLabel: "History",

  // Grow home
  growHeading: "Let's grow your business",
  growPlaceholder: "Increase my customer reach...",
  sections: [
    "Running Ads",
    "Social Media",
    "Cold Outreach",
    "Social Listening",
    "Organic Growth",
  ],
  runningAds: [
    "ChatGPT Ads",
    "Meta Ads",
    "Google Ads",
    "LinkedIn Ads",
    "Tiktok Ads",
  ],
  // The badge sitting on the ChatGPT Ads card — this is the "no ad account" beat.
  managedBadge: "Runable Managed",
  chatgptBadge: "ChatGPT",

  // Right rail
  rail: {
    websiteTitle: "Your Website",
    websiteEmpty: "Pick a default website and it will show up here.",
    setWebsite: "Set default website",
    contactTitle: "Contact details",
    contact: ["Set up email", "Get phone number"],
    handlesTitle: "Your handles",
    handles: [
      "Instagram",
      "Facebook",
      "X / Twitter",
      "Tiktok",
      "LinkedIn",
      "YouTube",
      "Reddit",
      "LINE",
    ],
    connect: "Connect",
    scheduled: "Scheduled Tasks",
  },

  // The Run Ads modal — the DEMO beat, verbatim from the live capture.
  runAds: {
    title: "Run Ads",
    subtitle: "Runable creates and manages ChatGPT Ads for you.",
    sendLabel: "Send visitors to",
    sendValue: "Your website created on Runable",
    setDefault: "Set default website",
    budgetLabel: "Daily budget",
    min: "$10",
    max: "$1000",
    // Real values observed while dragging the slider.
    feeLine: (n: number) => `$${n} to ads · $0 platform fee`,
    cta: (n: number) => `Run Ads ($${n}/day)`,
    footnote:
      "The first day comes from your ads balance. You approve that charge before anything runs.",
  },
} as const;

// ---------------------------------------------------------------------------
// STRIP LIST — Victor, Aug 27: "remove the free trial thing from Runable".
// The Build tab shows a "Free plan  ✨ Upgrade" pill above the composer.
// NEVER render it. Also omit the credit pill if a shot feels salesy.
// ---------------------------------------------------------------------------
export const DO_NOT_RENDER = [
  "Free plan",
  "Upgrade",
  "Get the App",
] as const;

// ---------------------------------------------------------------------------
// Real interface screenshots, for fragment insets. staticFile paths.
// ---------------------------------------------------------------------------
export const SHOTS = {
  buildHome: "bgrow/capture/01-build-home.png",
  growHome: "bgrow/capture/02-grow-home.png",
  adsModal: "bgrow/capture/03-chatgpt-ads-modal.png",
  adsBudget: "bgrow/capture/04-daily-budget-dragged.png",
  refAdsChatgpt: "bgrow/capture/ref-ads-chatgpt.png",
  refGrowHome: "bgrow/capture/ref-grow-home.png",
} as const;

// Official brand assets (downloaded from creatoros.runable.site/brand).
export const BRAND = {
  runableDark: "bgrow/brand/runable-dark.svg", // dark lockup, for LIGHT panels
  runableLight: "bgrow/brand/runable-light.svg", // light lockup, for DARK ground
  markDark: "bgrow/brand/runable-mark-dark.svg",
  markLight: "bgrow/brand/runable-mark-light.svg",
  merydianMark: "bgrow/merydian/merydianlogoicon.png", // green diamond, on dark
} as const;

// ---------------------------------------------------------------------------
// BRAND FACTS — keep exact. Source: RUNABLE-BRIEF.md + Bennett's final script.
// NOTE: the giveaway numbers are still flagged UNVERIFIED with the brand.
// ---------------------------------------------------------------------------
export const FACTS = {
  product: "Runable Grow", // full name, always
  giveawayTotal: "$1,000,000",
  giveawayEach: "$100",
  giveawaySpots: "10,000",
  retainer: "$2,000", // Bennett's own agency math, never ad results
  clients: 5,
  monthly: "$10,000",
  cta: "runable.com",
  commentKeyword: "RUN",
} as const;
