// Fish Audio 5 — shared board-room primitives.
// READ-ONLY for builder agents: import these, compose them in your own comp
// file with your own camera/world. Do not edit this file from a part build.
//
// ⚠️ Nothing here may render an advisor name — portraits only (compliance).

import React from "react";
import { Img, staticFile } from "remotion";
import {
  ADVISORS,
  ALTARI,
  AUDIO_LABEL,
  FISH,
  GRID_LINE,
  GRID_SIZE,
} from "./theme";

export type AdvisorKey = keyof typeof ADVISORS;

// ---------------------------------------------------------------------------
// AltariBackdrop — opaque Altari purple base + subtle 64px grid + vignette.
// MUST be the first child of every comp's root AbsoluteFill (no black frames).
// ---------------------------------------------------------------------------
export const AltariBackdrop: React.FC<{ width: number; height: number }> = ({
  width,
  height,
}) => (
  <div
    style={{
      position: "absolute",
      left: 0,
      top: 0,
      width,
      height,
      backgroundColor: ALTARI.bg,
      backgroundImage: `
        linear-gradient(${GRID_LINE} 1px, transparent 1px),
        linear-gradient(90deg, ${GRID_LINE} 1px, transparent 1px),
        radial-gradient(120% 100% at 50% 42%, rgba(91,94,194,0.10) 0%, rgba(26,26,46,0) 62%)
      `,
      backgroundSize: `${GRID_SIZE}px ${GRID_SIZE}px, ${GRID_SIZE}px ${GRID_SIZE}px, 100% 100%`,
    }}
  />
);

// ---------------------------------------------------------------------------
// PortraitOrb — circular advisor portrait with accent ring. `speak` (0..1+)
// drives the outer speaking-ring glow; keep the portrait itself static.
// Positioned by its CENTER at (x, y) in world coordinates.
// ---------------------------------------------------------------------------
export const PortraitOrb: React.FC<{
  advisor: AdvisorKey;
  x: number;
  y: number;
  size: number;
  enter?: number; // 0..1 entrance progress (scale + opacity)
  speak?: number; // 0..1 speaking-glow intensity
}> = ({ advisor, x, y, size, enter = 1, speak = 0 }) => {
  const a = ADVISORS[advisor];
  const ring = Math.max(3, Math.round(size * 0.022));
  return (
    <div
      style={{
        position: "absolute",
        left: x - size / 2,
        top: y - size / 2,
        width: size,
        height: size,
        opacity: enter,
        transform: `scale(${0.9 + enter * 0.1})`,
      }}
    >
      {/* speaking glow */}
      <div
        style={{
          position: "absolute",
          inset: -size * 0.14,
          borderRadius: "50%",
          background: `radial-gradient(circle, ${a.accentSoft} 0%, rgba(0,0,0,0) 68%)`,
          opacity: speak,
        }}
      />
      <div
        style={{
          position: "absolute",
          inset: 0,
          borderRadius: "50%",
          overflow: "hidden",
          border: `${ring}px solid ${a.accent}`,
          boxShadow: `0 0 ${size * 0.16 * speak}px ${a.accentSoft}`,
          backgroundColor: ALTARI.card2,
        }}
      >
        <Img
          src={staticFile(a.portrait)}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
          }}
        />
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// WaveBars — a row of animated audio bars. Pass `level` per-frame (0..1) and a
// deterministic seed offset; heights are pure functions of frame.
// Centered at (x, y), total width `w`.
// ---------------------------------------------------------------------------
export const WaveBars: React.FC<{
  frame: number;
  x: number;
  y: number;
  w: number;
  h: number;
  bars?: number;
  color: string;
  level: number; // 0 silent → 1 full
  seed?: number;
}> = ({ frame, x, y, w, h, bars = 24, color, level, seed = 0 }) => {
  const gap = w / bars;
  const items = [];
  for (let i = 0; i < bars; i++) {
    const ph = Math.sin(i * 1.7 + seed * 13.37) * 3.1;
    const speed = 0.55 + ((i * 7 + seed * 5) % 5) * 0.09;
    const wob =
      0.5 +
      0.5 *
        Math.sin(frame * speed * 0.35 + ph) *
        Math.sin(frame * 0.11 + i * 0.9);
    const bh = Math.max(h * 0.06, h * wob * level);
    items.push(
      <div
        key={i}
        style={{
          position: "absolute",
          left: x - w / 2 + i * gap + gap * 0.22,
          top: y - bh / 2,
          width: gap * 0.56,
          height: bh,
          borderRadius: gap * 0.28,
          backgroundColor: color,
        }}
      />,
    );
  }
  return <>{items}</>;
};

// ---------------------------------------------------------------------------
// AudioWaveBars — same geometry as WaveBars, but bar heights come from the REAL
// audio (FFT bins via @remotion/media-utils visualizeAudio). Pass `amplitudes`
// once the voice is playing; pass null before that (or while the audio file is
// still loading) and it falls back to the deterministic idle motion so the
// bars never sit dead. Centered at (x, y), total width `w`.
// ---------------------------------------------------------------------------
export type VoiceEnvelope = {
  hopSec: number;
  durationSec: number;
  env: number[];
};

export const AudioWaveBars: React.FC<{
  envelope: VoiceEnvelope;
  tSec: number | null; // playhead in the voice clip; null = not playing yet
  frame: number;
  x: number;
  y: number;
  w: number;
  h: number;
  bars?: number;
  color: string;
  level: number; // master gain 0..1 (entrance ramp)
  seed?: number;
  spreadSec?: number; // audio time spanned by the whole bar row
}> = ({
  envelope,
  tSec,
  frame,
  x,
  y,
  w,
  h,
  bars = 24,
  color,
  level,
  seed = 0,
  spreadSec = 0.9,
}) => {
  // Before the voice starts, keep the established idle motion.
  if (tSec === null) {
    return (
      <WaveBars
        frame={frame}
        x={x}
        y={y}
        w={w}
        h={h}
        bars={bars}
        color={color}
        level={level * 0.26}
        seed={seed}
      />
    );
  }

  const { env, hopSec } = envelope;
  const sampleAt = (t: number) => {
    const idxF = t / hopSec;
    if (idxF <= 0 || idxF >= env.length - 1) return 0;
    const i0 = Math.floor(idxF);
    return env[i0] + (env[i0 + 1] - env[i0]) * (idxF - i0);
  };

  const gap = w / bars;
  const items = [];
  for (let i = 0; i < bars; i++) {
    const u = bars === 1 ? 0.5 : i / (bars - 1);
    // Window centred on the playhead: the row reads left(past) → right(future),
    // so each syllable visibly sweeps across as it is spoken.
    const amp = sampleAt(tSec + (u - 0.5) * spreadSec);
    // Gentle taper so the row has a waveform silhouette rather than a block.
    const taper = 0.72 + 0.28 * Math.sin(Math.PI * u);
    const bh = Math.max(h * 0.06, h * amp * taper * level);
    items.push(
      <div
        key={i}
        style={{
          position: "absolute",
          left: x - w / 2 + i * gap + gap * 0.22,
          top: y - bh / 2,
          width: gap * 0.56,
          height: bh,
          borderRadius: gap * 0.28,
          backgroundColor: color,
        }}
      />,
    );
  }
  return <>{items}</>;
};

// ---------------------------------------------------------------------------
// VoicePill — "Voice generated by Fish Audio" (series-mandated on audio beats).
// Centered at (x, y). `enter` 0..1.
// ---------------------------------------------------------------------------
export const VoicePill: React.FC<{
  x: number;
  y: number;
  enter?: number;
  scale?: number;
}> = ({ x, y, enter = 1, scale = 1 }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      transform: `translate(-50%, -50%) scale(${scale * (0.94 + enter * 0.06)})`,
      opacity: enter,
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "12px 22px",
      borderRadius: 999,
      backgroundColor: "rgba(44, 44, 74, 0.85)",
      border: `1px solid ${ALTARI.border}`,
      whiteSpace: "nowrap",
    }}
  >
    <div
      style={{
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: FISH.orange,
      }}
    />
    <span
      style={{
        fontFamily:
          "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        fontSize: 24,
        fontWeight: 600,
        color: ALTARI.body,
      }}
    >
      {AUDIO_LABEL}
    </span>
  </div>
);

// ---------------------------------------------------------------------------
// CreamCard — the fish4 editorial cream card (curl-card language). Children
// render on the cream surface. Positioned by top-left in world coordinates.
// ---------------------------------------------------------------------------
export const CreamCard: React.FC<{
  x: number;
  y: number;
  w: number;
  h?: number;
  enter?: number;
  children?: React.ReactNode;
}> = ({ x, y, w, h, enter = 1, children }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      width: w,
      height: h,
      borderRadius: 28,
      backgroundColor: ALTARI.cream,
      boxShadow: "0 24px 80px rgba(0,0,0,0.42)",
      opacity: enter,
      transform: `translateY(${(1 - enter) * 26}px)`,
      overflow: "hidden",
    }}
  >
    {children}
  </div>
);

// ---------------------------------------------------------------------------
// FishChip — small "Fish Audio · S2.1 PRO" brand chip (fish4 convention).
// Centered at (x, y).
// ---------------------------------------------------------------------------
export const FishChip: React.FC<{
  x: number;
  y: number;
  enter?: number;
  scale?: number;
}> = ({ x, y, enter = 1, scale = 1 }) => (
  <div
    style={{
      position: "absolute",
      left: x,
      top: y,
      transform: `translate(-50%, -50%) scale(${scale})`,
      opacity: enter,
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: "14px 26px",
      borderRadius: 16,
      backgroundColor: "rgba(20, 20, 42, 0.9)",
      border: `1px solid ${ALTARI.border}`,
      whiteSpace: "nowrap",
    }}
  >
    {/* NOTE: the fish-audio PNGs are mislabeled on disk — logo-dark.png holds
        the WHITE wordmark (correct for this dark chip), logo-light.png the
        dark one. Verified 2026-08-25. */}
    <Img
      src={staticFile(FISH.logoDark)}
      style={{ height: 30, objectFit: "contain" }}
    />
    <span
      style={{
        fontFamily:
          "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        fontSize: 26,
        fontWeight: 700,
        letterSpacing: 2,
        color: ALTARI.amber,
      }}
    >
      S2.1 PRO
    </span>
  </div>
);
