// Fish Audio 5 — F5P13NumberOneBlindTests (1080x1080, 240f @ 30fps)
// VO: "S2.1 Pro is number one in blind tests, and the emotion tags are what
//      make them sound like people who disagree instead of one narrator doing
//      three accents."
//
// Beat map — one continuous world, two destinations:
//   f0–14    open tight on the #1 row of the cream leaderboard card; the row
//            pulses in with a warm flare; score "3.07" springs in
//   f14–38   camera pulls out to the full card; greeked competitor rows
//            stagger in (no invented names — bars only)
//   f38–56   hold while the rank underline draws under "Fish Audio S2.1 Pro"
//   f56–74   camera travels right/down to the emotion-tag demo panel
//   f74–176  hold: ONE sentence waveform; tag chips activate at f90/f125/f160
//            and the SAME waveform morphs into a visibly different silhouette
//            in that advisor's accent color — one chip active at a time
//   f176–200 pull out to the settle framing: leaderboard + tri-color waveform
//   f200–239 settle hold; FishChip lands at f200; final two camera keys equal
//
// Compliance: no advisor names, no competitor names, no narration echo.
// On-screen text: "#1", "Fish Audio S2.1 Pro", "3.07", the three bracketed
// tag chips (product input), the FishChip brand chip, and the series-mandated
// "Voice generated by Fish Audio" audio label (theme.ts convention).
import React from "react";
import {
  AbsoluteFill,
  Easing,
  interpolate,
  interpolateColors,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { loadFont as loadManrope } from "@remotion/google-fonts/Manrope";
import { loadFont as loadMono } from "@remotion/google-fonts/JetBrainsMono";
import { ADVISORS, ALTARI, FISH, FISH_UI, NUMBERS, SPRINGS } from "./theme";
import { AltariBackdrop, CreamCard, FishChip, VoicePill } from "./board";

const { fontFamily: manropeFamily } = loadManrope("normal", {
  weights: ["600", "700", "800"],
});
const { fontFamily: monoFamily } = loadMono("normal", {
  weights: ["500", "700"],
});

export const DURATION_IN_FRAMES = 240;

const W = 1080;
const H = 1080;

// ---------------------------------------------------------------------------
// World geometry
// ---------------------------------------------------------------------------
// Leaderboard card (destination one)
const CARD_X = 140;
const CARD_Y = 180;
const CARD_W = 800;
const CARD_H = 640;
// #1 row (card-local)
const ROW_X = 48;
const ROW_Y = 56;
const ROW_W = 704;
const ROW_H = 148; // #1 row world-center y ≈ 310; opening focal y = 335

// Emotion-tag demo panel (destination two)
const PANEL_X = 620;
const PANEL_Y = 1060;
const PANEL_W = 920;
const PANEL_H = 560;
const PANEL_CX = PANEL_X + PANEL_W / 2; // 1080
// Waveform (panel-local)
const WAVE_CY = 300;
const WAVE_W = 780;
const WAVE_HMAX = 200;
const BARS = 54;

// Chip activation frames (one active at a time)
const ACT = [90, 125, 160] as const;
const TRI_AT = 180; // tri-color settle state begins
const MORPH = 14;

const CHIPS = [
  // Actual emotion words, matching theme VOICE_INPUTS (Victor, Aug 25)
  { tag: "[impatient]", accent: ADVISORS.operator.accent, soft: ADVISORS.operator.accentSoft },
  { tag: "[calm]", accent: ADVISORS.editor.accent, soft: ADVISORS.editor.accentSoft },
  { tag: "[amused]", accent: ADVISORS.longgame.accent, soft: ADVISORS.longgame.accentSoft },
] as const;

// ---------------------------------------------------------------------------
// Deterministic helpers + waveform silhouettes (pure functions of t / i)
// ---------------------------------------------------------------------------
const fract = (x: number) => x - Math.floor(x);
const rnd = (i: number) => fract(Math.sin((i + 1) * 12.9898) * 43758.5453);
const bell = (t: number, c: number, s: number) =>
  Math.exp(-((t - c) * (t - c)) / (2 * s * s));
const clamp01 = (v: number) => Math.min(1, Math.max(0, v));

type StageK = "neutral" | "op" | "ed" | "lg" | "tri";

// idle murmur — low, even
const envNeutral = (t: number) => 0.14 + 0.05 * Math.sin(t * 8 + 1);
// blunt, impatient — jagged spikes, front-loaded, hard gaps
const envOp = (t: number, i: number) => {
  const spik = Math.pow(Math.abs(Math.sin(t * 22 + 0.8)), 0.6);
  const chop = 0.55 + 0.45 * rnd(i * 7 + 3);
  return (0.26 + 0.66 * spik * chop) * (1.06 - 0.22 * t);
};
// quiet, unhurried — one low smooth swell, small tail
const envEd = (t: number) =>
  0.1 + 0.3 * bell(t, 0.42, 0.14) + 0.1 * bell(t, 0.8, 0.06);
// measured, amused — moderate undulation rising into a question-lift
const envLg = (t: number) =>
  0.28 + 0.13 * Math.sin(t * 11 + 0.4) + 0.24 * t * t;
// settle payoff — same line as three different people, one segment each
const SEG_GAP = 0.024;
const envTri = (t: number, i: number) => {
  if (Math.abs(t - 1 / 3) < SEG_GAP || Math.abs(t - 2 / 3) < SEG_GAP)
    return 0.07;
  if (t < 1 / 3) return envOp(t * 3, i) * 0.8;
  if (t < 2 / 3) return envEd((t - 1 / 3) * 3) * 1.25;
  return envLg((t - 2 / 3) * 3) * 0.92;
};

const envFor = (k: StageK, t: number, i: number): number => {
  switch (k) {
    case "neutral":
      return envNeutral(t);
    case "op":
      return envOp(t, i);
    case "ed":
      return envEd(t);
    case "lg":
      return envLg(t);
    case "tri":
      return envTri(t, i);
  }
};

const colorFor = (k: StageK, t: number): string => {
  switch (k) {
    case "neutral":
      return ALTARI.faint;
    case "op":
      return CHIPS[0].accent;
    case "ed":
      return CHIPS[1].accent;
    case "lg":
      return CHIPS[2].accent;
    case "tri":
      return t < 1 / 3
        ? CHIPS[0].accent
        : t < 2 / 3
          ? CHIPS[1].accent
          : CHIPS[2].accent;
  }
};

// Stage machine: which silhouette we are morphing from/to at this frame
const stageAt = (frame: number): { from: StageK; to: StageK; p: number } => {
  const steps: Array<[number, StageK]> = [
    [ACT[0], "op"],
    [ACT[1], "ed"],
    [ACT[2], "lg"],
    [TRI_AT, "tri"],
  ];
  let idx = -1;
  for (let s = 0; s < steps.length; s++) {
    if (frame >= steps[s][0]) idx = s;
  }
  if (idx === -1) return { from: "neutral", to: "neutral", p: 1 };
  const from: StageK = idx === 0 ? "neutral" : steps[idx - 1][1];
  const p = Easing.out(Easing.cubic)(clamp01((frame - steps[idx][0]) / MORPH));
  return { from, to: steps[idx][1], p };
};

// Parallax stars (fish4 starfield language) — deterministic, subtle
const buildStars = () => {
  const pts = [];
  for (let i = 0; i < 26; i++) {
    pts.push({
      x: 60 + rnd(i * 3 + 1) * 1700,
      y: 40 + rnd(i * 5 + 2) * 1720,
      r: 0.9 + rnd(i * 7 + 3) * 1.7,
      o: 0.1 + rnd(i * 11 + 4) * 0.22,
      ph: rnd(i * 13 + 5) * Math.PI * 2,
    });
  }
  return pts;
};

// Greeked competitor rows — bars only, no invented names (compliance)
const GREEK_ROWS = [
  { y: 252, nameW: 300, tone: 0.16 },
  { y: 348, nameW: 254, tone: 0.14 },
  { y: 444, nameW: 286, tone: 0.12 },
  { y: 540, nameW: 232, tone: 0.1 },
];

export const F5P13NumberOneBlindTests: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const ease = Easing.inOut(Easing.cubic);

  // -------------------------------------------------------------------------
  // Camera — one shared keyframe timeline, hold → move → hold
  // -------------------------------------------------------------------------
  const KEY_T = [0, 14, 38, 56, 74, 176, 200, 232, 239];
  const camOpts = {
    easing: ease,
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  } as const;
  const fx = interpolate(
    frame,
    KEY_T,
    [540, 540, 540, 540, PANEL_CX, PANEL_CX, 840, 840, 840],
    camOpts,
  );
  const fy = interpolate(
    frame,
    KEY_T,
    [335, 335, 500, 500, 1370, 1370, 920, 920, 920],
    camOpts,
  );
  const z = interpolate(
    frame,
    KEY_T,
    [1.3, 1.3, 1.0, 1.0, 1.0, 1.0, 0.6, 0.6, 0.6],
    camOpts,
  );

  const stars = React.useMemo(buildStars, []);

  // Gentle vertical floats (micro-motion; horizontal stays fixed for margins)
  const cardFloat = 3 * Math.sin(frame * 0.045);
  const panelFloat = 3 * Math.sin(frame * 0.05 + 2.1);

  // -------------------------------------------------------------------------
  // Leaderboard beats
  // -------------------------------------------------------------------------
  // #1 row pulses in with a warm flare — pre-rolled 4f so the opening frame
  // is already mid-pulse ("open tight on something already moving")
  const rowIn = spring({
    frame: frame + 4,
    fps,
    config: SPRINGS.smooth,
    durationInFrames: 18,
  });
  const flareS = spring({
    frame: frame + 4,
    fps,
    config: SPRINGS.snappy,
    durationInFrames: 24,
  });
  const flareO = interpolate(frame, [0, 8, 26, 46], [0.3, 0.85, 0.45, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const rankIn = spring({
    frame: frame + 4,
    fps,
    config: SPRINGS.snappy,
    durationInFrames: 22,
  });
  const nameIn = spring({
    frame: frame - 1,
    fps,
    config: SPRINGS.smooth,
    durationInFrames: 20,
  });
  // Row highlight border breathes softly after the flare
  const rowPulse = 0.62 + 0.16 * Math.sin(frame * 0.09);

  // Rank underline draws during the f38–56 hold
  const underlineT = interpolate(frame, [40, 56], [0, 1], {
    easing: Easing.out(Easing.cubic),
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // -------------------------------------------------------------------------
  // Emotion-tag demo beats
  // -------------------------------------------------------------------------
  const panelIn = spring({
    frame: frame - 58,
    fps,
    config: SPRINGS.smooth,
    durationInFrames: 24,
  });
  const waveO = interpolate(frame, [66, 80], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const { from, to, p } = stageAt(frame);
  // Wobble amplitude: idle → speaking → settled
  const speakAmt = interpolate(frame, [86, 92, 176, 196], [0, 1, 1, 0.25], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const wobAmp = 0.12 + 0.2 * speakAmt;
  const centerGlowColor = interpolateColors(
    p,
    [0, 1],
    [colorFor(from, 0.5), colorFor(to, 0.5)],
  );

  const pillIn = spring({
    frame: frame - 96,
    fps,
    config: SPRINGS.smooth,
    durationInFrames: 24,
  });

  // -------------------------------------------------------------------------
  // Settle beats
  // -------------------------------------------------------------------------
  const chipLand = spring({
    frame: frame - 200,
    fps,
    config: SPRINGS.snappy,
    durationInFrames: 26,
  });

  return (
    <AbsoluteFill style={{ backgroundColor: ALTARI.bg }}>
      {/* Opaque backdrop, frame 0 → last (no black frames) */}
      <AltariBackdrop width={W} height={H} />

      {/* ------------------------- WORLD (camera rig) ---------------------- */}
      <div
        style={{
          position: "absolute",
          transform: `translate(${W / 2 - fx}px, ${H / 2 - fy}px) scale(${z})`,
          transformOrigin: `${fx}px ${fy}px`,
        }}
      >
        {/* parallax stars */}
        <svg
          style={{ position: "absolute", left: 0, top: 0, overflow: "visible" }}
          width={1}
          height={1}
        >
          {stars.map((s, i) => (
            <circle
              key={i}
              cx={s.x}
              cy={s.y}
              r={s.r}
              fill={ALTARI.primaryLight}
              opacity={s.o * (0.65 + 0.35 * Math.sin(frame * 0.04 + s.ph))}
            />
          ))}
        </svg>

        {/* ----------------- destination one: leaderboard ----------------- */}
        <div style={{ position: "absolute", top: cardFloat }}>
          <CreamCard x={CARD_X} y={CARD_Y} w={CARD_W} h={CARD_H}>
            {/* warm flare behind the #1 row */}
            <div
              style={{
                position: "absolute",
                left: ROW_X + ROW_W / 2 - 330,
                top: ROW_Y + ROW_H / 2 - 130,
                width: 660,
                height: 260,
                borderRadius: "50%",
                background:
                  "radial-gradient(closest-side, rgba(242,200,143,0.85) 0%, rgba(232,162,91,0.35) 45%, rgba(232,162,91,0) 72%)",
                transform: `scale(${0.4 + flareS * 0.75})`,
                opacity: flareO,
              }}
            />

            {/* #1 row — highlighted */}
            <div
              style={{
                position: "absolute",
                left: ROW_X,
                top: ROW_Y,
                width: ROW_W,
                height: ROW_H,
                borderRadius: 18,
                backgroundColor: "rgba(91, 94, 194, 0.10)",
                border: `2.5px solid rgba(91, 94, 194, ${rowPulse})`,
                boxShadow: `0 0 ${22 * rowIn}px rgba(123, 125, 214, 0.35)`,
                opacity: rowIn,
                transform: `translateY(${(1 - rowIn) * 12}px)`,
              }}
            >
              <div
                style={{
                  position: "absolute",
                  left: 34,
                  top: 42,
                  fontFamily: manropeFamily,
                  fontWeight: 800,
                  fontSize: 62,
                  lineHeight: 1,
                  color: ALTARI.creamInk,
                  opacity: rankIn,
                  transform: `scale(${0.7 + rankIn * 0.3})`,
                  transformOrigin: "left center",
                }}
              >
                {NUMBERS.blindTestRank}
              </div>
              <div
                style={{
                  position: "absolute",
                  left: 150,
                  top: 50,
                  fontFamily: manropeFamily,
                  fontWeight: 700,
                  fontSize: 34,
                  lineHeight: 1,
                  color: ALTARI.creamInk,
                  whiteSpace: "nowrap",
                  opacity: nameIn,
                  transform: `translateX(${(1 - nameIn) * -16}px)`,
                }}
              >
                {FISH_UI.modelPicker}
              </div>
              {/* rank underline — draws during the hold */}
              <div
                style={{
                  position: "absolute",
                  left: 150,
                  top: 98,
                  width: 307 * underlineT,
                  height: 5,
                  borderRadius: 3,
                  backgroundColor: FISH.orange,
                  opacity: underlineT > 0 ? 0.95 : 0,
                }}
              />
              {/* Bradley-Terry score REMOVED (Fish Audio revision, Aug 27
                  2026): 3.07 is S2 Pro's score, not S2.1 Pro's. The "#1 in
                  blind tests" claim is still approved — the number is not. */}
            </div>

            {/* dashed divider (fish4 card language) */}
            <div
              style={{
                position: "absolute",
                left: ROW_X,
                top: 226,
                width: ROW_W,
                borderTop: "2px dashed rgba(31, 31, 51, 0.22)",
                opacity: rowIn,
              }}
            />

            {/* greeked competitor rows — bars only, no names */}
            {GREEK_ROWS.map((g, i) => {
              const gIn = interpolate(
                frame,
                [10 + i * 6, 24 + i * 6],
                [0, 1],
                {
                  easing: Easing.out(Easing.cubic),
                  extrapolateLeft: "clamp",
                  extrapolateRight: "clamp",
                },
              );
              return (
                <div
                  key={i}
                  style={{
                    position: "absolute",
                    left: ROW_X,
                    top: g.y,
                    width: ROW_W,
                    height: 48,
                    opacity: gIn,
                    transform: `translateX(${(1 - gIn) * 16}px)`,
                  }}
                >
                  <div
                    style={{
                      position: "absolute",
                      left: 0,
                      top: 14,
                      width: 40,
                      height: 20,
                      borderRadius: 6,
                      backgroundColor: `rgba(31, 31, 51, ${g.tone + 0.04})`,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      left: 66,
                      top: 14,
                      width: g.nameW,
                      height: 20,
                      borderRadius: 10,
                      backgroundColor: `rgba(31, 31, 51, ${g.tone})`,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      right: 0,
                      top: 14,
                      width: 72,
                      height: 20,
                      borderRadius: 10,
                      backgroundColor: `rgba(31, 31, 51, ${g.tone - 0.02})`,
                    }}
                  />
                </div>
              );
            })}
          </CreamCard>
        </div>

        {/* --------------- destination two: emotion-tag demo --------------- */}
        <div
          style={{
            position: "absolute",
            left: PANEL_X,
            top: PANEL_Y + panelFloat + (1 - panelIn) * 36,
            width: PANEL_W,
            height: PANEL_H,
            borderRadius: 24,
            backgroundColor: ALTARI.card2,
            border: `1px solid ${ALTARI.border}`,
            boxShadow: "0 28px 80px rgba(0, 0, 0, 0.45)",
            opacity: panelIn,
          }}
        >
          {/* tag chips — product input text */}
          <div
            style={{
              position: "absolute",
              left: 40,
              right: 40,
              top: 52,
              display: "flex",
              justifyContent: "center",
              gap: 20,
            }}
          >
            {CHIPS.map((c, i) => {
              const aStart = ACT[i];
              const aEnd = i < 2 ? ACT[i + 1] : TRI_AT;
              const glow = interpolate(
                frame,
                [aStart, aStart + 10, aEnd, aEnd + 12],
                [0, 1, 1, 0.45],
                {
                  extrapolateLeft: "clamp",
                  extrapolateRight: "clamp",
                },
              );
              const bump =
                frame >= aStart && frame <= aStart + 16
                  ? Math.sin((Math.PI * (frame - aStart)) / 16)
                  : 0;
              const chipO = interpolate(
                frame,
                [64 + i * 4, 76 + i * 4],
                [0, 1],
                {
                  extrapolateLeft: "clamp",
                  extrapolateRight: "clamp",
                },
              );
              const textCol = interpolateColors(
                glow,
                [0, 1],
                [ALTARI.faint, c.accent],
              );
              const borderCol = interpolateColors(
                glow,
                [0, 1],
                [ALTARI.border, c.accent],
              );
              return (
                <div
                  key={i}
                  style={{
                    position: "relative",
                    padding: "12px 20px",
                    borderRadius: 12,
                    border: `1.5px solid ${borderCol}`,
                    backgroundColor: ALTARI.bgDeep,
                    opacity: chipO,
                    transform: `scale(${1 + 0.04 * glow + 0.06 * bump})`,
                    boxShadow:
                      glow > 0.02
                        ? `0 0 ${18 * glow}px ${c.soft}`
                        : "none",
                  }}
                >
                  <div
                    style={{
                      position: "absolute",
                      inset: 0,
                      borderRadius: 12,
                      backgroundColor: c.soft,
                      opacity: glow,
                    }}
                  />
                  <span
                    style={{
                      position: "relative",
                      fontFamily: monoFamily,
                      fontWeight: 500,
                      fontSize: 21,
                      whiteSpace: "nowrap",
                      color: textCol,
                    }}
                  >
                    {c.tag}
                  </span>
                </div>
              );
            })}
          </div>

          {/* soft accent glow behind the waveform */}
          <div
            style={{
              position: "absolute",
              left: PANEL_W / 2 - 350,
              top: WAVE_CY - 110,
              width: 700,
              height: 220,
              borderRadius: "50%",
              background: `radial-gradient(closest-side, ${centerGlowColor} 0%, rgba(0,0,0,0) 72%)`,
              opacity: 0.13 * waveO * (0.4 + 0.6 * speakAmt),
            }}
          />

          {/* faint centerline */}
          <div
            style={{
              position: "absolute",
              left: PANEL_W / 2 - WAVE_W / 2,
              top: WAVE_CY - 1,
              width: WAVE_W,
              height: 2,
              backgroundColor: "rgba(110, 112, 168, 0.25)",
              opacity: waveO,
            }}
          />

          {/* THE sentence waveform — same line, morphing silhouette */}
          {Array.from({ length: BARS }).map((_, i) => {
            const t = i / (BARS - 1);
            const hFrom = envFor(from, t, i);
            const hTo = envFor(to, t, i);
            const env = hFrom + (hTo - hFrom) * p;
            const sp = 0.5 + 0.35 * rnd(i * 3 + 11);
            const ph = rnd(i * 5 + 17) * Math.PI * 2;
            const wob = 1 - wobAmp + wobAmp * Math.sin(frame * sp + ph);
            const h = Math.max(6, WAVE_HMAX * env * wob);
            const gap = WAVE_W / BARS;
            const col = interpolateColors(
              p,
              [0, 1],
              [colorFor(from, t), colorFor(to, t)],
            );
            return (
              <div
                key={i}
                style={{
                  position: "absolute",
                  left: PANEL_W / 2 - WAVE_W / 2 + i * gap + gap * 0.21,
                  top: WAVE_CY - h / 2,
                  width: gap * 0.58,
                  height: h,
                  borderRadius: gap * 0.29,
                  backgroundColor: col,
                  opacity: waveO,
                }}
              />
            );
          })}

          {/* series-mandated audio label */}
          <VoicePill
            x={PANEL_W / 2}
            y={498}
            enter={pillIn}
            scale={0.92}
          />
        </div>

        {/* FishChip lands at f200 during the settle */}
        {frame >= 198 && (
          <FishChip
            x={1360}
            y={460 + 2 * Math.sin(frame * 0.05)}
            enter={Math.min(1, chipLand * 1.3)}
            scale={1.4 * (1.18 - 0.18 * chipLand)}
          />
        )}
      </div>
    </AbsoluteFill>
  );
};
