// Shared DNA for the Fish Audio 5 series (Aug 2026) — "The board talks back".
// STYLE: Altari purple (Ahmed's design language), continuing the fish4 system:
// Altari starfield world, cream editorial cards, orange voice orb, grid backdrop.
// Sequel to Ahmed's BOARD reel — three advisors (portraits in
// public/fish5/portraits/) get Fish Audio voices and argue with each other.
//
// ⚠️ COMPLIANCE (Fish Audio, Aug 17 2026): the advisor NAMES must NEVER appear
// as on-screen text. Portraits are approved; name labels are not. No "Hormozi",
// "Rubin", "Naval", "HORMOZI VOICE" etc. anywhere in rendered pixels.
//
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

export const ALTARI = {
  // Surfaces (Altari purple world)
  bg: "#1A1A2E",
  bgDeep: "#14142A",
  card: "#2C2C4A",
  card2: "#252542",
  border: "#3D3D60",

  // Brand purples
  primary: "#5B5EC2",
  primaryLight: "#7B7DD6",
  primaryDeep: "#3D2C8D",

  // Text
  heading: "#FFFFFF",
  body: "#A5A7D9",
  faint: "#6E70A8",

  // States
  green: "#4ECD9B",
  red: "#E85D5D",
  amber: "#E8A25B",

  // Cream editorial card (fish4 curl-card language)
  cream: "#F4EDDC",
  creamInk: "#1F1F33",
} as const;

// The three advisors. Referenced by ROLE, never by name (see compliance note).
// Portrait files exist but carry names only in the filename (production-only).
export const ADVISORS = {
  operator: {
    // blunt numbers guy (Hormozi-lens)
    portrait: "fish5/portraits/hormozi-keyed.png", // transparent bg (green keyed out)
    accent: "#E85D5D",
    accentSoft: "rgba(232, 93, 93, 0.22)",
  },
  editor: {
    // quiet cut-things-down guy (Rubin-lens)
    portrait: "fish5/portraits/rubin.jpg",
    accent: "#EDE6D2",
    accentSoft: "rgba(237, 230, 210, 0.20)",
  },
  longgame: {
    // measured better-question guy (Naval-lens)
    portrait: "fish5/portraits/naval.jpg",
    accent: "#7B7DD6",
    accentSoft: "rgba(123, 125, 214, 0.24)",
  },
} as const;

// Ahmed's presence in the room = warm amber orb (fish4 convention).
export const AHMED_ORB = {
  orb: "#E8A25B",
  orbLite: "#F2C88F",
} as const;

// Fish Audio brand (from fish.audio site; files in public/fish-audio/)
export const FISH = {
  logoLight: "fish-audio/logo-light.png", // white wordmark for dark bg
  logoDark: "fish-audio/logo-dark.png",
  orange: "#FF4F00", // fish.audio accent
} as const;

// REAL strings — captured from fish.audio on 2026-08-20 (fish4 capture).
export const API = {
  endpoint: "https://api.fish.audio/v1/tts",
  model: "s2.1-pro-free",
  curl: [
    "curl -X POST \\",
    "  https://api.fish.audio/v1/tts \\",
    '  -H "Authorization: Bearer $FISH_API_KEY" \\',
    '  -H "Content-Type: application/json" \\',
    '  -H "model: s2.1-pro-free" \\',
    "  -d '{\"text\": \"Hello! Welcome to Fish Audio.\"}' \\",
    "  --output welcome.mp3",
  ],
  voiceDesignEndpoint: "https://api.fish.audio/v1/voice-design",
  voiceDesignModel: "voice-design-1",
} as const;

// Emotion-tag inputs for the four VOICE lines. These are PRODUCT INPUT text —
// allowed on screen because they demo the emotion-tag feature.
//
// These strings are the LITERAL generation input — the exact text sent to the
// TTS API, character for character. Per the sponsor's revision note (Aug 27
// 2026): "make sure the emotion tags are included in the actual generation
// input, not just shown during editing" and "stack specific, natural-language
// tags — for example [calm but firm] [slow, deliberate delivery] — instead of
// using only one broad tag." That supersedes the earlier single-word rule.
// If you change a string here you MUST regenerate its audio from the same
// string (scratchpad/fishcap/el-descriptive.mjs), or the card starts lying.
export const VOICE_INPUTS = {
  operator1:
    "[blunt, impatient] [clipped, rapid delivery] Your pricing is wrong. [flat, dismissive] You're anchoring off your costs again.",
  operator2:
    "[urgent, leaning in] [decisive, no hedging] Don't raise the retainer. [conspiratorial, landing hard on the number] Add five thousand for the consulting you're already giving away.",
  editor1:
    "[calm but firm] [slow, deliberate delivery] And cut the deck in half. [gently amused, almost a shrug] The pitch is doing too much talking.",
  longgame1:
    "[knowing, quietly amused] [unhurried, letting it land] Ask a better question. [genuinely curious, leaning in] Does this client get you the next ten?",
} as const;

// REAL UI strings — captured logged-in from fish.audio/app on 2026-08-25.
// Screenshots: public/fish5/site/app-tts-emotion-tag.png, app-create-voice.png.
// Use these verbatim in UI fragments; do not invent product copy.
export const FISH_UI = {
  ttsPlaceholder:
    "Type your text with audio tags like [laughs] to turn into expressive speech...",
  modelPicker: "Fish Audio S2.1 Pro",
  modelFreePill: "Free",
  generateBtn: "Generate Speech",
  autoTag: "Auto Tag",
  tagsBtn: "Tags",
  charCounter: "/ 500 characters",
  addSpeaker: "Add Speaker",
  pickMethod: "Pick a method",
  voiceDesignTitle: "Voice Design",
  voiceDesignDesc: "Describe the voice in plain text.",
  voiceDesignTime: "~15s",
  voiceDesignBest: "Best for original characters",
} as const;

// Required on every audio demo beat (series convention since fish4).
export const AUDIO_LABEL = "Voice generated by Fish Audio";

// Numbers cleared for use (creative brief; carried from fish4).
export const NUMBERS = {
  blindTestRank: "#1",
  bradleyTerry: "3.07",
  languages: 83,
  ttfaMs: 70,
  tokensPerSec: "8,000+",
  proposal: "$15,000",
  addOn: "+$5,000",
  answerSeconds: "11.0",
} as const;

// Springs (Liam skill presets)
export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule).
export const safePadX = (width: number) => Math.round(width * 0.05);

// Altari 64px grid backdrop (keep subtle under the starfield)
export const GRID_SIZE = 64;
export const GRID_LINE = "rgba(91, 94, 194, 0.07)";
