// Shared DNA for the Polsia series (Aug 2026, LIAM WHITE + Polsia editorial).
// Source of truth: real captures in public/polsia/reference/ — polsia.com home,
// /live dashboard, /login, /new onboarding, and Victor's signed-in dashboard
// (papp-*.png) captured while Polsia autonomously built a company.
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

// ---------------------------------------------------------------------------
// World (Liam white) + Polsia editorial surfaces
// ---------------------------------------------------------------------------
export const WORLD = {
  bg: "#F7F6F3", // warm white world base (Liam standard)
  card: "#FFFFFF",
  border: "#E8E6E1",
  borderSoft: "rgba(0, 0, 0, 0.05)",
  text: "#1A1A1A",
  muted: "#8A867E",
  faint: "#B7B3AA",
  shadow: "0 18px 50px rgba(20, 18, 12, 0.10), 0 2px 8px rgba(20, 18, 12, 0.05)",
  shadowSoft: "0 10px 30px rgba(20, 18, 12, 0.07)",
  radius: 24,
} as const;

export const POLSIA = {
  // Product surfaces (the real app is stark white with hairline black rules)
  paper: "#FFFFFF",
  ink: "#111111",
  rule: "#111111", // 1-2px black section underlines (editorial)
  grayText: "#6F6F6F",
  cardGray: "#F2F2F2", // task/feed cards
  // Accent
  orange: "#E65100", // ticker bar, live dot (sampled from computed styles)
  // Terminal strip (black bar at the very top of every page)
  termBg: "#000000",
  termText: "#FFFFFF",
  // Mono button chip (GET STARTED style: dark gradient, mono, letterspaced)
  btnBg: "linear-gradient(#3A3A3A, #171717)",
  btnText: "#FFFFFF",
} as const;

// REAL UI strings — captured from the live product, do not invent.
export const STRINGS = {
  ticker: "● WATCH POLSIA WORK ON 21,658 COMPANIES LIVE →",
  tagline: "AI That Runs Your Company While You Sleep",
  taglines2: ["You're a founder, or you should be.", "Polsia is your first employee. Never sleeps.", "The solo founder's standing army.", "One name. Every role.", "Start a company tonight"],
  getStarted: "GET STARTED",
  createCompany: "CREATE A NEW COMPANY",
  growCompany: "GROW MY COMPANY",
  buildMyIdea: "Build my idea",
  surpriseMe: "Surprise me",
  letsGetStarted: "Let's get started.",
  letsBuild: "Let's build something.",
  freeToStart: "NO CREDIT CARD REQUIRED · FREE TO START",
  menu: "Menu ▾",
  signIn: "SIGN IN",
  live: "● LIVE",
  ceoReport: "Day 33 — CEO Report",
  terminal: [
    "> Ready when you are.",
    "> Reading your brief and getting my bearings.",
    "> Setting up your company's home base on Polsia.",
    "> Studying your market — who's out there and where the demand is.",
    "> Deep searching web for: AI invoice agent automation tools",
    "> Turning the research into a crisp company profile.",
    "> Deploying marketing campaign...",
    "> Processing autonomous tasks...",
    "> Waiting for live data...",
  ],
  moods: {
    investigating: { label: "Investigating", sub: "Figuring out the approach" },
    researching: { label: "Researching", sub: "Studying your market…" },
    brainstorming: { label: "Brainstorming", sub: "Shaping your company…" },
    curious: { label: "Curious", sub: "Booting..." },
  },
} as const;

// REAL /live data (allowed on screen — product data, not narration echo)
export const LIVE = {
  stats: [
    { label: "Active Companies:", value: 21658, delta: "+19% WOW" },
    { label: "Human Messages Sent:", value: 3870979, delta: "+5% WOW" },
    { label: "Tasks Completed:", value: 2012640, delta: "+1% WOW" },
    { label: "Emails Sent:", value: 1056627, delta: "+6% WOW" },
  ],
  companies: ["Tramo", "TalaTuro", "Hatchhaul", "Hostwarden", "Cultifur"],
  tags: ["RESEARCH", "META_ADS"],
  companiesPerDay: "+ 5,087 companies launched in the past 24h",
  tasksPerDay: "+ 302 tasks completed in the past 24h",
} as const;

// The REAL ASCII mascot faces, straight from the app DOM (<pre class="polsia-ascii">).
// Render in Suisse-Mono-style monospace with pre-wrap. Animate by swapping faces
// and micro-bobbing; the thought dots (○) trail below when thinking.
export const FACES = {
  investigating: "  ╭─────────╮\n  │  ◉   ◉  │\n  │    ▽    │\n  │   ◡◡◡   │\n  ╰─────────╯\n      ○\n     ○",
  researching: "┌─────────┐\n│  ◉   ⊙  │\n│    ▽    │\n│   ◡◡◡   │\n└─────────┘",
  brainstorming: "┌─────────┐\n│ ╱■■■■■╲ │ ✧\n│    ▽    │\n│   ◡◡◡   │\n└─────────┘",
  curious: "┌─────────┐\n│  ⌒   ⌒  │\n│    ▽    │\n│    人    │\n└─────────┘",
} as const;

// Assets via staticFile
export const ASSETS = {
  wordmark: "polsia/polsia-logonoir.webp", // serif "Polsia" wordmark, 772x301, black on transparent
  liveCapture: "polsia/polsia-live-capture.mp4", // 34s real /live page recording, 1440x900
} as const;

// Type: Polsia uses "Editorial New" (serif) + "Suisse Mono". Use loaded lookalikes:
export const FONT_SERIF = '"Editorial New", "Playfair Display", "Times New Roman", Georgia, serif';
export const FONT_MONO = '"Suisse Mono", "IBM Plex Mono", "Courier New", ui-monospace, monospace';
export const FONT_SANS = 'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif';

export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule: 54px on 1080-wide canvases).
export const safePadX = (width: number) => Math.round(width * 0.05);
