// Shared Notion-interface DNA for the notion-cli series (Aug 2026, WHITE).
// Source of truth: real screenshots in public/notion/reference/ —
// Victor's live workspace (notion-app-home.png) + notion.com/product UI cards.
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

export const NOTION = {
  // Surfaces
  bg: "#FFFFFF",
  sidebar: "#F7F7F5",
  hoverRow: "#F1F1EF",
  selected: "#EFEFED",
  banner: "#E8F3F8", // light blue "page is live" banner

  // Text
  text: "#191919",
  textSoft: "#37352F",
  muted: "#787774",
  faint: "#9B9A97",
  linkBlue: "#2383E2",

  // Lines
  border: "#E9E9E7",
  borderSoft: "rgba(0, 0, 0, 0.06)",

  // Accent (Notion blue button)
  blue: "#2383E2",
  blueHover: "#1B76CB",

  // Problem/pain accent (series-level, used sparingly)
  red: "#EB5757",
  redSoft: "#FFE2DD",

  // Success/automation
  green: "#448361",
  greenSoft: "#DBEDDB",
} as const;

// Notion tag-pill palette (bg + text), matches real property pills.
export const PILL = {
  gray: { bg: "#E3E2E0", text: "#32302C" },
  brown: { bg: "#EEE0DA", text: "#442A1E" },
  orange: { bg: "#FADEC9", text: "#49290E" },
  yellow: { bg: "#FDECC8", text: "#402C1B" },
  green: { bg: "#DBEDDB", text: "#1C3829" },
  blue: { bg: "#D3E5EF", text: "#183347" },
  purple: { bg: "#E8DEEE", text: "#412454" },
  pink: { bg: "#F5E0E9", text: "#4C2337" },
  red: { bg: "#FFE2DD", text: "#5D1715" },
} as const;

// Notion app font stack (what the real UI renders in).
export const FONT_SANS =
  'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif';
export const FONT_MONO =
  '"SFMono-Regular", ui-monospace, "Cascadia Mono", "Roboto Mono", Menlo, Consolas, monospace';

// Springs (Liam skill presets)
export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule).
export const safePadX = (width: number) => Math.round(width * 0.05);

// Real Notion CLI commands (from developers.notion.com/cli — do not invent).
export const CLI = {
  install: "curl -fsSL https://ntn.dev | bash",
  version: "ntn --version",
  login: "ntn login",
  apiPages: "ntn api v1/pages",
  apiUsers: "ntn api v1/users",
  workersNew: "ntn workers new",
  workersDeploy: "ntn workers deploy",
  workersList: "ntn workers list",
} as const;
