// Shared DNA for the KOEN x RUNABLE "viral shorts agent" reel (Aug 2026).
// 9 parts, all 1080x1080, LIAM WHITE STYLE with a screen-recording feel.
//
// The world is Liam's warm white. Runable's real product UI renders in its own
// authentic cream/near-white and floats as cards on that world. Runable's amber
// is the accent. Dark lives ONLY inside cards (the black submit button, video
// frames, YouTube thumbnails).
//
// EVERY string below was read off the REAL app while logged in on 2026-08-28,
// or off Koen's REAL YouTube channel. Screenshots backing every claim live in
// public/kshorts/reference/ (canonical copies in the working folder at
// CREATORS/Koen/Reels/brand deals/Runable/references/capture/).
//
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

// ---------------------------------------------------------------- Liam world
export const LW = {
  paper: "#F7F6F3", // the warm white world (Liam default)
  paperDeep: "#EFEDE8", // subtle floor gradient / inset
  card: "#FFFFFF", // floating white card
  cardSoft: "#FBFAF8",
  hairline: "rgba(0,0,0,0.07)", // card border
  hairlineSoft: "rgba(0,0,0,0.04)",
  ink: "#141414", // headings
  body: "#4A4A48", // body copy
  muted: "#8A8A85", // labels, captions
  shadow: "0 18px 44px rgba(23,20,14,0.10), 0 2px 6px rgba(23,20,14,0.05)",
  shadowLift: "0 34px 80px rgba(23,20,14,0.14), 0 4px 10px rgba(23,20,14,0.06)",
} as const;

// ------------------------------------------------------- Runable product UI
export const RN = {
  bg: "#FEFDFB", // app background
  panel: "#F4F1EE", // sidebar / composer well
  hover: "#F3EFEB",
  card: "#FFFFFF",
  ink: "#111111", // black submit arrow / primary button
  text: "#060606",
  textWarm: "#3D2E24",
  muted: "#6B5A50",
  border: "rgba(0,0,0,0.05)",
  borderStrong: "rgba(0,0,0,0.10)",
  amber: "#DE9B4A", // THE accent for this series
  amberSoft: "rgba(222,155,74,0.12)",
  cyan: "#00B7CA", // active feature chip
  green: "#1DA25A",
} as const;

// Platform marks used in this reel (P7 schedule, P9 multi-platform).
export const PLATFORM = {
  youtube: "#FF0000",
  instagram: "#E1306C",
  tiktok: "#000000",
  tiktokCyan: "#25F4EE",
  tiktokRed: "#FE2C55",
} as const;

export const FONT_SANS =
  'IDGrotesk, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';
export const FONT_DISPLAY =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Helvetica, Arial, sans-serif';
export const FONT_MONO =
  '"SFMono-Regular", ui-monospace, Menlo, Consolas, monospace';

export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule). 54px on a 1080 canvas.
export const safePadX = (width: number) => Math.round(width * 0.05);

// ===========================================================================
// DO NOT RENDER — Victor's standing art-direction bans for Runable renders.
// ===========================================================================
export const DO_NOT_RENDER = [
  "The 'Free plan / Upgrade' pill above the composer. It appears in the real screenshot (10-composer-typed.png) but must NEVER appear in a render.",
  "Victor's own name/avatar in the sidebar. This is KOEN's world: the signed-in user reads 'Koen' or is cropped out of frame entirely.",
  "The 'Send Now On Runable' ad card that appears in real chat transcripts.",
  "Any on-screen text that restates the narration (see the skill's hard rule).",
] as const;

// ===========================================================================
// THE SCRIPT — verbatim from the LIVE Notion page (Brand Deals Koen Hub →
// Runable row → "Runable Reel Script", page 9c5404ba-a655-4cd0-903e-094d89ef0209,
// last edited 2026-08-23). This supersedes the older local KOEN-RUNABLE-SCRIPT.md
// which still carried "ten shorts" and the Bigfoot-title placeholders.
// VO only — none of this may be rendered as on-screen copy.
// ===========================================================================
export const VO = {
  p1: "Build me an agent that turns any video into viral shorts and posts them to my YouTube channel.",
  p2: "Insane.",
  p3: "Usually, I'd have to watch the whole video, find the best moments, cut them, caption them, write titles, and upload everything myself.",
  p4: "So here's exactly what Runable did, start to finish.",
  p5a: "First, it wrote its own instructions.",
  p5b: "Then it transcribed my video.",
  p6a: "Found the most viral moments.",
  p6b: "Cut every clip vertical.",
  p7a: "Put the captions right on.",
  p7b: "Wrote the titles. And scheduled all of them straight to my channel.",
  p8: "That would normally take me a full day of editing, every single video.",
  p9a: "Runable can actually help you automate growing your channels, and it doesnt just post to YouTube, it can post to Instagram and TikTok too.",
  p9b: "One sentence in Runable built that whole agent flow. Comment RUN and I'll send you the link to try it.",
} as const;

// ===========================================================================
// REAL RUNABLE UI STRINGS (live capture, 2026-08-28, logged-in account).
// Do not invent product copy. If it is not here, look at the screenshots.
// ===========================================================================
export const UI = {
  // Build tab composer — 10-composer-typed.png
  heading: "What needs to be done?",
  placeholder: "Describe what you want Runable to build...",
  modeAgent: "Agent",
  modeAsk: "Ask",
  model: "Auto",
  plan: "Plan",
  featuresLabel: "Features in Agent mode",
  features: [
    "Websites",
    "Slides",
    "Report",
    "Sheets",
    "Workflows",
    "Apps",
    "Video",
    "Image",
    "Audio",
    "Carousels",
    "Link-in-Bio",
    "SaaS",
    "Blog",
  ],
  shuffle: "Shuffle",
  nav: ["New task", "Artifacts", "Flow", "Claw", "Meet", "Customize"],
  credits: "1.5k",

  // The task Runable actually named this run, in History — 12-q1.png
  taskName: "Viral Shorts YouTube Agent",

  // The real clarifying-question card — 12-q1.png. Six questions, numbered
  // options, a free-text field, Skip/Next, and dot pagination.
  qCounter: (n: number, total = 6) => `Question ${n} of ${total}`,
  q1Title: "Which shape do you want?",
  q1Options: [
    "A web app I build for you — paste a URL or upload a video, it clips + captions the best moments, you review, then one click uploads to YouTube",
    "A hands-off scheduled agent — I run the pipeline in the background on a schedule (watch a channel/playlist, clip, auto-post) with no UI",
    "Both — start with the web app, add scheduling later",
  ],
  answerPlaceholder: "Type your answer",
  skip: "Skip",
  next: "Next",
  stepsDone: (n: number) => `Completed ${n} step${n === 1 ? "" : "s"}`,
  thinking: "Thinking...",

  // Skills page — 06-skills.png. THIS is the "wrote its own instructions" beat.
  skills: {
    title: "Skills",
    line: "Skills help you create outcomes with repeatability.",
    search: "Search for skills",
    create: "Create a Skill",
    active: "Active Skills",
    on: "On",
    official: "Official",
    tabs: ["Personalization", "Workflows", "Plugins", "Skills"],
  },

  // Plugins page — 03-plugins.png
  plugins: {
    title: "Plugins",
    line: "Connect your apps to use them with Runable.",
    search: "Search for plugins",
    addCustom: "Add Custom Plugin",
    included: "Included with Runable",
  },

  // Grow tab right rail — 00-probe.png. Real connect targets for P9.
  handles: {
    title: "Your handles",
    connect: "Connect",
    list: [
      "Instagram",
      "Facebook",
      "X / Twitter",
      "Tiktok",
      "LinkedIn",
      "YouTube",
      "Reddit",
      "LINE",
    ],
  },
  scheduledTasks: "Scheduled Tasks",
} as const;

// The skill the agent writes in P5. Runable's own Skills page describes skills
// as reusable instruction sets — this is the shape, named for Koen's job.
export const SKILL_FILE = {
  name: "viral-shorts-pipeline",
  desc: "Download a video, transcribe it, pick the highest-retention moments, cut them 9:16, burn in captions, write titles, and publish to the connected channel.",
  badge: "On",
} as const;

// ===========================================================================
// THE CHANNEL — captured 2026-08-28 from youtube.com/@BEHINDTHEACTION-2/shorts.
// Screenshot: public/kshorts/reference/yt-bta-shorts.png (1600x1000 viewport,
// page scrolled so BOTH shelf rows are in frame).
//
// Victor, 2026-08-28: use this channel, and "skip the first 5 shorts". The grid
// is 6-across, so the first clean row that clears his cut is ROW 2 = shorts
// 7-12. Everything featured in close-up comes from that row.
//
// SHELF geometry below is measured off THIS capture. Row 2 is the shelf row.
// ===========================================================================
export const CHANNEL = {
  name: "BEHIND THE ACTION",
  handle: "@BEHINDTHEACTION-2",
  subs: "15.9K subscribers",
  videos: "16 videos",
  tabs: ["Shorts"],
  filters: ["Latest", "Popular", "Oldest"],
} as const;

// Where the thumbnails sit inside yt-bta-shorts.png, in source pixels.
// ROW is the row we feature (row 2 — the first five shorts are skipped).
export const SHELF = {
  rowY: 177, // featured row (shorts 7-12) — the skipped ones are offscreen
  nextRowY: 580, // the following row, for scroll context
  w: 207,
  h: 325,
  x: (n: number) => 265 + n * 218,
  capH: 78, // title + view-count block beneath each thumbnail
} as const;

// Real Shorts from ROW 2, left to right, with real view counts.
// `short` is the two-line truncation YouTube itself renders on the shelf —
// use it wherever the full title will not fit.
export const SHORTS = [
  {
    title:
      "Tiny Bullet Train vs Fighter Jet | Behind The movie Set Explosion!",
    short: "Tiny Bullet Train vs Fighter Jet | Behind Th\u2026",
    views: "185K views",
  },
  {
    title: "How We Destroyed a Giant Castle with Pirate Cannons | Ai VFX",
    short: "How We Destroyed a Giant Castle with Pirat\u2026",
    views: "202K views",
  },
  {
    title: "Hollywood style Ai Cinematic VFX action Clips | Nuclear Plant",
    short: "Hollywood style Ai Cinematic VFX action \u2026",
    views: "395K views",
  },
  {
    title: "Behind the Scenes of an Epic Water Stunt!",
    short: "Behind the Scenes of an Epic Water Stunt!",
    views: "30K views",
  },
  {
    title:
      "Behind the Scenes | Miniature Airplane Crash Landing on a Giant Bridge",
    short: "Behind the Scenes | Miniature Airplane Cra\u2026",
    views: "585K views",
  },
  {
    title:
      "Human Enters a Capsule... A Monster Breaks Out! | Epic AI Cinematic",
    short: "Human Enters a Capsule\u2026 A Monster \u2026",
    views: "524K views",
  },
] as const;

// The pipeline the agent ran, as six ordered steps. This is the visual spine
// across P4-P7. Labels are SHORT and describe the MECHANISM (allowed) — they
// are not restatements of the VO line (banned).
export const STEPS = [
  { n: 1, label: "skill written", icon: "skill" },
  { n: 2, label: "transcript", icon: "transcript" },
  { n: 3, label: "moments picked", icon: "spark" },
  { n: 4, label: "9:16 cut", icon: "crop" },
  { n: 5, label: "captions burned", icon: "caption" },
  { n: 6, label: "titled + scheduled", icon: "send" },
] as const;

// Real tool chain the agent named in-account (Aug 22 chat, "Automatic Video
// Download, Clipping, and YouTube Posting"). Safe to show as terminal text.
export const TOOLS = {
  download: "yt-dlp",
  clip: "ffmpeg",
  note: "transcript-based moment picking",
} as const;

// Reference screenshots for fragment insets (staticFile paths).
export const SHOTS = {
  composerTyped: "kshorts/reference/10-composer-typed.png",
  questionCard: "kshorts/reference/12-q1.png",
  skills: "kshorts/reference/06-skills.png",
  plugins: "kshorts/reference/03-plugins.png",
  growHandles: "kshorts/reference/00-probe.png",
  ytShorts: "kshorts/reference/yt-bta-shorts.png",
  ytHome: "kshorts/reference/yt-bta-shorts.png",
} as const;

export const RUNABLE_MARK = "kshorts/runable-mark.svg";
