// Shared DNA for the Lovable x Wispr Flow series (Aug 2026, LIAM WHITE).
// Source of truth: real captures in public/lovable/reference/ —
// Victor's logged-in Lovable dashboard/editor (app-0*.png) + lovable.dev home,
// wisprflow.ai home, and the Dronea hook video frames (hook-0*.png).
// READ-ONLY for builder agents: import tokens, build your own layout in your
// own comp file. Do not edit this file from a part build.

// ---------------------------------------------------------------------------
// Liam white world (series base — backgrounds, cards, type)
// ---------------------------------------------------------------------------
export const WORLD = {
  bg: "#F7F6F3", // warm white world base
  card: "#FFFFFF",
  border: "#E8E6E1",
  borderSoft: "rgba(0, 0, 0, 0.05)",
  text: "#1A1A1A",
  muted: "#8A867E",
  faint: "#B7B3AA",
  shadow: "0 18px 50px rgba(20, 18, 12, 0.10), 0 2px 8px rgba(20, 18, 12, 0.05)",
  shadowSoft: "0 10px 30px rgba(20, 18, 12, 0.07)",
  radius: 24,
} as const;

// ---------------------------------------------------------------------------
// Lovable product DNA (from real logged-in captures)
// ---------------------------------------------------------------------------
export const LOVABLE = {
  // UI surfaces (the app is white/neutral; the gradient lives on the dashboard bg)
  ui: "#FFFFFF",
  uiBorder: "#ECEAE6",
  text: "#171717",
  muted: "#8F8C86",
  black: "#111111", // black pill buttons ("Get started", send arrow)
  // Dashboard hero gradient (top→bottom: warm white → blue → pink → red)
  gradient: ["#F6F4EF", "#4D7EF2", "#E24FB4", "#F4385C"],
  // Small accent when a single color is needed (send button hover / links)
  accent: "#2563EB",
  // REAL UI strings — do not invent (captured 2026-08-23)
  strings: {
    ready: "Ready to build, Liam?", // real: "Ready to build, Victor?" — series identity is Liam
    placeholder: "Ask Lovable to create a",
    build: "Build",
    attachMenu: ["Attach", "Connectors", "Databases"],
    sendAria: "Send message",
    voiceAria: "Start voice recording",
    plusAria: "Additional actions",
    thinking: "Thinking",
    loadingPreview: "Loading Live Preview...",
    preview: "Preview",
    homepage: "Homepage",
    projectName: "Dronea Launchpad",
    workspace: "Liam's Lovable",
    followUp: "Send follow-up...",
  },
  logoSvg: "lovable/lovable-logo.svg", // heart glyph, gradient (staticFile)
  iconSvg: "lovable/lovable-icon.svg",
  iconPng: "lovable/lovable-icon.png",
} as const;

// ---------------------------------------------------------------------------
// Wispr Flow product DNA (from wisprflow.ai captures + official CDN SVGs)
// ---------------------------------------------------------------------------
export const WISPR = {
  cream: "#FFFDF0", // page background
  green: "#0B4A3F", // deep brand green sections
  lavender: "#EFE1FD", // "Get started on macOS" chip
  lavenderBorder: "#C9AFEA",
  ink: "#1A1A1A",
  // The real dictation bar (Flowbar): dark pill #1A1A1A, stroke #4D4A42,
  // white waveform ticks. Official vector: wispr-flowbar.svg.
  barBg: "#1A1A1A",
  barStroke: "#4D4A42",
  // REAL data from wisprflow.ai — allowed on screen (product data, not narration)
  data: { keyboardWpm: 45, flowWpm: 220, claim: "4x faster than typing" },
  logoSvg: "lovable/wispr-navbar-logo.svg", // "|||| Flow" wordmark
  flowbarSvg: "lovable/wispr-flowbar.svg", // the dictation pill itself
  micSvg: "lovable/wispr-mic-icon.svg",
  faviconPng: "lovable/wispr-favicon.png",
} as const;

// ---------------------------------------------------------------------------
// Dronea (the 3D site being built — from the hook video frames)
// ---------------------------------------------------------------------------
export const DRONEA = {
  paper: "#EDECE7", // site background (warm off-white)
  ink: "#111111",
  gray: "#9B988F", // "(ISR)" gray in headline
  // Real site strings visible in the reference video (UI text, allowed)
  nav: ["New Arrival", "All Product", "Drone Camera", "Support"],
  headlineA: ["Jet-", "Powered", "(ISR) Drone", "Concept"],
  headlineB: ["Deep-", "Strike", "(UCAV) Jet", "Concept"],
  cta: "Explore the Design",
  ctaSecondary: "See Demo",
  brand: "Dronea",
  video: "lovable/thebuggeddev-hook.mp4", // 2936x1846 @60fps, 27.1s (staticFile)
} as const;

// ---------------------------------------------------------------------------
// Type + motion (Liam skill presets)
// ---------------------------------------------------------------------------
export const FONT_SANS =
  'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';
export const FONT_SERIF = '"Times New Roman", Georgia, serif'; // Wispr headline style only
export const FONT_MONO =
  '"SFMono-Regular", ui-monospace, Menlo, Consolas, monospace';

export const SPRINGS = {
  snappy: { damping: 20, stiffness: 200 },
  smooth: { damping: 200, stiffness: 100 },
  bouncy: { damping: 10, stiffness: 140 },
  heavy: { damping: 16, stiffness: 80, mass: 1.6 },
} as const;

// 5% side safe margin helper (hard rule: 54px on 1080-wide canvases).
export const safePadX = (width: number) => Math.round(width * 0.05);
